/*
 * iDGARD UIAPI
 * This API is intended for internal usage only. No guarantees regarding completeness of documentation and API stability are given.  Swagger UI available at: <a href=\"/assets/idgapi/doc/index.html\">&lt;server&gt;/assets/idgapi/doc/index.html</a>  Redoc not available due to API size 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.idgard.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * only for upload in a DR-box
 */
@Schema(description = "only for upload in a DR-box")


public class EntryERM {
  @JsonProperty("disableInheritanceFromParent")
  private Boolean disableInheritanceFromParent = null;

  public EntryERM disableInheritanceFromParent(Boolean disableInheritanceFromParent) {
    this.disableInheritanceFromParent = disableInheritanceFromParent;
    return this;
  }

   /**
   * Get disableInheritanceFromParent
   * @return disableInheritanceFromParent
  **/
  @Schema(description = "")
  public Boolean isDisableInheritanceFromParent() {
    return disableInheritanceFromParent;
  }

  public void setDisableInheritanceFromParent(Boolean disableInheritanceFromParent) {
    this.disableInheritanceFromParent = disableInheritanceFromParent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntryERM entryERM = (EntryERM) o;
    return Objects.equals(this.disableInheritanceFromParent, entryERM.disableInheritanceFromParent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disableInheritanceFromParent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntryERM {\n");
    
    sb.append("    disableInheritanceFromParent: ").append(toIndentedString(disableInheritanceFromParent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
