/*
 * iDGARD UIAPI
 * This API is intended for internal usage only. No guarantees regarding completeness of documentation and API stability are given.  Swagger UI available at: <a href=\"/assets/idgapi/doc/index.html\">&lt;server&gt;/assets/idgapi/doc/index.html</a>  Redoc not available due to API size 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.idgard.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import ch.cyberduck.core.idgard.io.swagger.client.model.Membership;
import ch.cyberduck.core.idgard.io.swagger.client.model.PrefilledOtaInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OtaInfo
 */



public class OtaInfo {
  @JsonProperty("requiresPasscode")
  private Boolean requiresPasscode = null;

  @JsonProperty("requiresName")
  private Boolean requiresName = null;

  @JsonProperty("requiresCaptcha")
  private Boolean requiresCaptcha = null;

  @JsonProperty("membership")
  private Membership membership = null;

  @JsonProperty("preferAnonymous")
  private Boolean preferAnonymous = null;

  @JsonProperty("prefilledInfo")
  private PrefilledOtaInfo prefilledInfo = null;

  @JsonProperty("csfrToken")
  private String csfrToken = null;

  public OtaInfo requiresPasscode(Boolean requiresPasscode) {
    this.requiresPasscode = requiresPasscode;
    return this;
  }

   /**
   * Get requiresPasscode
   * @return requiresPasscode
  **/
  @Schema(description = "")
  public Boolean isRequiresPasscode() {
    return requiresPasscode;
  }

  public void setRequiresPasscode(Boolean requiresPasscode) {
    this.requiresPasscode = requiresPasscode;
  }

  public OtaInfo requiresName(Boolean requiresName) {
    this.requiresName = requiresName;
    return this;
  }

   /**
   * Get requiresName
   * @return requiresName
  **/
  @Schema(description = "")
  public Boolean isRequiresName() {
    return requiresName;
  }

  public void setRequiresName(Boolean requiresName) {
    this.requiresName = requiresName;
  }

  public OtaInfo requiresCaptcha(Boolean requiresCaptcha) {
    this.requiresCaptcha = requiresCaptcha;
    return this;
  }

   /**
   * Get requiresCaptcha
   * @return requiresCaptcha
  **/
  @Schema(description = "")
  public Boolean isRequiresCaptcha() {
    return requiresCaptcha;
  }

  public void setRequiresCaptcha(Boolean requiresCaptcha) {
    this.requiresCaptcha = requiresCaptcha;
  }

  public OtaInfo membership(Membership membership) {
    this.membership = membership;
    return this;
  }

   /**
   * Get membership
   * @return membership
  **/
  @Schema(description = "")
  public Membership getMembership() {
    return membership;
  }

  public void setMembership(Membership membership) {
    this.membership = membership;
  }

  public OtaInfo preferAnonymous(Boolean preferAnonymous) {
    this.preferAnonymous = preferAnonymous;
    return this;
  }

   /**
   * Get preferAnonymous
   * @return preferAnonymous
  **/
  @Schema(description = "")
  public Boolean isPreferAnonymous() {
    return preferAnonymous;
  }

  public void setPreferAnonymous(Boolean preferAnonymous) {
    this.preferAnonymous = preferAnonymous;
  }

  public OtaInfo prefilledInfo(PrefilledOtaInfo prefilledInfo) {
    this.prefilledInfo = prefilledInfo;
    return this;
  }

   /**
   * Get prefilledInfo
   * @return prefilledInfo
  **/
  @Schema(description = "")
  public PrefilledOtaInfo getPrefilledInfo() {
    return prefilledInfo;
  }

  public void setPrefilledInfo(PrefilledOtaInfo prefilledInfo) {
    this.prefilledInfo = prefilledInfo;
  }

  public OtaInfo csfrToken(String csfrToken) {
    this.csfrToken = csfrToken;
    return this;
  }

   /**
   * Get csfrToken
   * @return csfrToken
  **/
  @Schema(description = "")
  public String getCsfrToken() {
    return csfrToken;
  }

  public void setCsfrToken(String csfrToken) {
    this.csfrToken = csfrToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtaInfo otaInfo = (OtaInfo) o;
    return Objects.equals(this.requiresPasscode, otaInfo.requiresPasscode) &&
        Objects.equals(this.requiresName, otaInfo.requiresName) &&
        Objects.equals(this.requiresCaptcha, otaInfo.requiresCaptcha) &&
        Objects.equals(this.membership, otaInfo.membership) &&
        Objects.equals(this.preferAnonymous, otaInfo.preferAnonymous) &&
        Objects.equals(this.prefilledInfo, otaInfo.prefilledInfo) &&
        Objects.equals(this.csfrToken, otaInfo.csfrToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requiresPasscode, requiresName, requiresCaptcha, membership, preferAnonymous, prefilledInfo, csfrToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtaInfo {\n");
    
    sb.append("    requiresPasscode: ").append(toIndentedString(requiresPasscode)).append("\n");
    sb.append("    requiresName: ").append(toIndentedString(requiresName)).append("\n");
    sb.append("    requiresCaptcha: ").append(toIndentedString(requiresCaptcha)).append("\n");
    sb.append("    membership: ").append(toIndentedString(membership)).append("\n");
    sb.append("    preferAnonymous: ").append(toIndentedString(preferAnonymous)).append("\n");
    sb.append("    prefilledInfo: ").append(toIndentedString(prefilledInfo)).append("\n");
    sb.append("    csfrToken: ").append(toIndentedString(csfrToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
