/*
 * iDGARD UIAPI
 * This API is intended for internal usage only. No guarantees regarding completeness of documentation and API stability are given.  Swagger UI available at: <a href=\"/assets/idgapi/doc/index.html\">&lt;server&gt;/assets/idgapi/doc/index.html</a>  Redoc not available due to API size 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.idgard.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import ch.cyberduck.core.idgard.io.swagger.client.model.CompanyStorageStat;
import ch.cyberduck.core.idgard.io.swagger.client.model.License;
import ch.cyberduck.core.idgard.io.swagger.client.model.PacketFeature;
import ch.cyberduck.core.idgard.io.swagger.client.model.UsedUserLicense;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * QCOPacket
 */



public class QCOPacket {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("info")
  private List<String> info = null;

  @JsonProperty("fullLicenses")
  private UsedUserLicense fullLicenses = null;

  @JsonProperty("basicLicenses")
  private UsedUserLicense basicLicenses = null;

  @JsonProperty("guestLicenses")
  private UsedUserLicense guestLicenses = null;

  @JsonProperty("datarooms")
  private License datarooms = null;

  @JsonProperty("storage")
  private License storage = null;

  @JsonProperty("companyStorageDetailledStatus")
  private CompanyStorageStat companyStorageDetailledStatus = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("packagePrice")
  private Double packagePrice = null;

  @JsonProperty("trialPeriod")
  private Integer trialPeriod = null;

  @JsonProperty("configurable")
  private Boolean configurable = null;

  @JsonProperty("saving")
  private Double saving = null;

  @JsonProperty("features")
  private List<PacketFeature> features = null;

  @JsonProperty("binding")
  private String binding = null;

  @JsonProperty("booked")
  private Boolean booked = null;

  public QCOPacket id(String id) {
    this.id = id;
    return this;
  }

   /**
   * InventoryPacket
   * @return id
  **/
  @Schema(description = "InventoryPacket")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public QCOPacket name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public QCOPacket description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public QCOPacket info(List<String> info) {
    this.info = info;
    return this;
  }

  public QCOPacket addInfoItem(String infoItem) {
    if (this.info == null) {
      this.info = new ArrayList<>();
    }
    this.info.add(infoItem);
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  @Schema(description = "")
  public List<String> getInfo() {
    return info;
  }

  public void setInfo(List<String> info) {
    this.info = info;
  }

  public QCOPacket fullLicenses(UsedUserLicense fullLicenses) {
    this.fullLicenses = fullLicenses;
    return this;
  }

   /**
   * Get fullLicenses
   * @return fullLicenses
  **/
  @Schema(description = "")
  public UsedUserLicense getFullLicenses() {
    return fullLicenses;
  }

  public void setFullLicenses(UsedUserLicense fullLicenses) {
    this.fullLicenses = fullLicenses;
  }

  public QCOPacket basicLicenses(UsedUserLicense basicLicenses) {
    this.basicLicenses = basicLicenses;
    return this;
  }

   /**
   * Get basicLicenses
   * @return basicLicenses
  **/
  @Schema(description = "")
  public UsedUserLicense getBasicLicenses() {
    return basicLicenses;
  }

  public void setBasicLicenses(UsedUserLicense basicLicenses) {
    this.basicLicenses = basicLicenses;
  }

  public QCOPacket guestLicenses(UsedUserLicense guestLicenses) {
    this.guestLicenses = guestLicenses;
    return this;
  }

   /**
   * Get guestLicenses
   * @return guestLicenses
  **/
  @Schema(description = "")
  public UsedUserLicense getGuestLicenses() {
    return guestLicenses;
  }

  public void setGuestLicenses(UsedUserLicense guestLicenses) {
    this.guestLicenses = guestLicenses;
  }

  public QCOPacket datarooms(License datarooms) {
    this.datarooms = datarooms;
    return this;
  }

   /**
   * Get datarooms
   * @return datarooms
  **/
  @Schema(description = "")
  public License getDatarooms() {
    return datarooms;
  }

  public void setDatarooms(License datarooms) {
    this.datarooms = datarooms;
  }

  public QCOPacket storage(License storage) {
    this.storage = storage;
    return this;
  }

   /**
   * Get storage
   * @return storage
  **/
  @Schema(description = "")
  public License getStorage() {
    return storage;
  }

  public void setStorage(License storage) {
    this.storage = storage;
  }

  public QCOPacket companyStorageDetailledStatus(CompanyStorageStat companyStorageDetailledStatus) {
    this.companyStorageDetailledStatus = companyStorageDetailledStatus;
    return this;
  }

   /**
   * Get companyStorageDetailledStatus
   * @return companyStorageDetailledStatus
  **/
  @Schema(description = "")
  public CompanyStorageStat getCompanyStorageDetailledStatus() {
    return companyStorageDetailledStatus;
  }

  public void setCompanyStorageDetailledStatus(CompanyStorageStat companyStorageDetailledStatus) {
    this.companyStorageDetailledStatus = companyStorageDetailledStatus;
  }

  public QCOPacket currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(description = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public QCOPacket packagePrice(Double packagePrice) {
    this.packagePrice = packagePrice;
    return this;
  }

   /**
   * Get packagePrice
   * @return packagePrice
  **/
  @Schema(description = "")
  public Double getPackagePrice() {
    return packagePrice;
  }

  public void setPackagePrice(Double packagePrice) {
    this.packagePrice = packagePrice;
  }

  public QCOPacket trialPeriod(Integer trialPeriod) {
    this.trialPeriod = trialPeriod;
    return this;
  }

   /**
   * Get trialPeriod
   * @return trialPeriod
  **/
  @Schema(description = "")
  public Integer getTrialPeriod() {
    return trialPeriod;
  }

  public void setTrialPeriod(Integer trialPeriod) {
    this.trialPeriod = trialPeriod;
  }

  public QCOPacket configurable(Boolean configurable) {
    this.configurable = configurable;
    return this;
  }

   /**
   * specify if one can switch to other packet or not (which means must stay in the same packet), only avaiable if this packet is the booked one.
   * @return configurable
  **/
  @Schema(description = "specify if one can switch to other packet or not (which means must stay in the same packet), only avaiable if this packet is the booked one.")
  public Boolean isConfigurable() {
    return configurable;
  }

  public void setConfigurable(Boolean configurable) {
    this.configurable = configurable;
  }

  public QCOPacket saving(Double saving) {
    this.saving = saving;
    return this;
  }

   /**
   * Get saving
   * @return saving
  **/
  @Schema(description = "")
  public Double getSaving() {
    return saving;
  }

  public void setSaving(Double saving) {
    this.saving = saving;
  }

  public QCOPacket features(List<PacketFeature> features) {
    this.features = features;
    return this;
  }

  public QCOPacket addFeaturesItem(PacketFeature featuresItem) {
    if (this.features == null) {
      this.features = new ArrayList<>();
    }
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @Schema(description = "")
  public List<PacketFeature> getFeatures() {
    return features;
  }

  public void setFeatures(List<PacketFeature> features) {
    this.features = features;
  }

  public QCOPacket binding(String binding) {
    this.binding = binding;
    return this;
  }

   /**
   * Contractbinding: either ANNUAL or MONTHLY
   * @return binding
  **/
  @Schema(description = "Contractbinding: either ANNUAL or MONTHLY")
  public String getBinding() {
    return binding;
  }

  public void setBinding(String binding) {
    this.binding = binding;
  }

  public QCOPacket booked(Boolean booked) {
    this.booked = booked;
    return this;
  }

   /**
   * tells if this is currently booked or not
   * @return booked
  **/
  @Schema(description = "tells if this is currently booked or not")
  public Boolean isBooked() {
    return booked;
  }

  public void setBooked(Boolean booked) {
    this.booked = booked;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QCOPacket qcOPacket = (QCOPacket) o;
    return Objects.equals(this.id, qcOPacket.id) &&
        Objects.equals(this.name, qcOPacket.name) &&
        Objects.equals(this.description, qcOPacket.description) &&
        Objects.equals(this.info, qcOPacket.info) &&
        Objects.equals(this.fullLicenses, qcOPacket.fullLicenses) &&
        Objects.equals(this.basicLicenses, qcOPacket.basicLicenses) &&
        Objects.equals(this.guestLicenses, qcOPacket.guestLicenses) &&
        Objects.equals(this.datarooms, qcOPacket.datarooms) &&
        Objects.equals(this.storage, qcOPacket.storage) &&
        Objects.equals(this.companyStorageDetailledStatus, qcOPacket.companyStorageDetailledStatus) &&
        Objects.equals(this.currency, qcOPacket.currency) &&
        Objects.equals(this.packagePrice, qcOPacket.packagePrice) &&
        Objects.equals(this.trialPeriod, qcOPacket.trialPeriod) &&
        Objects.equals(this.configurable, qcOPacket.configurable) &&
        Objects.equals(this.saving, qcOPacket.saving) &&
        Objects.equals(this.features, qcOPacket.features) &&
        Objects.equals(this.binding, qcOPacket.binding) &&
        Objects.equals(this.booked, qcOPacket.booked);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, info, fullLicenses, basicLicenses, guestLicenses, datarooms, storage, companyStorageDetailledStatus, currency, packagePrice, trialPeriod, configurable, saving, features, binding, booked);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QCOPacket {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    fullLicenses: ").append(toIndentedString(fullLicenses)).append("\n");
    sb.append("    basicLicenses: ").append(toIndentedString(basicLicenses)).append("\n");
    sb.append("    guestLicenses: ").append(toIndentedString(guestLicenses)).append("\n");
    sb.append("    datarooms: ").append(toIndentedString(datarooms)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("    companyStorageDetailledStatus: ").append(toIndentedString(companyStorageDetailledStatus)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    packagePrice: ").append(toIndentedString(packagePrice)).append("\n");
    sb.append("    trialPeriod: ").append(toIndentedString(trialPeriod)).append("\n");
    sb.append("    configurable: ").append(toIndentedString(configurable)).append("\n");
    sb.append("    saving: ").append(toIndentedString(saving)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    binding: ").append(toIndentedString(binding)).append("\n");
    sb.append("    booked: ").append(toIndentedString(booked)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
