/*
 * iDGARD UIAPI
 * This API is intended for internal usage only. No guarantees regarding completeness of documentation and API stability are given.  Swagger UI available at: <a href=\"/assets/idgapi/doc/index.html\">&lt;server&gt;/assets/idgapi/doc/index.html</a>  Redoc not available due to API size 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.idgard.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * RestIdgardBody
 */



public class RestIdgardBody {
  @JsonProperty("bonuscode")
  private String bonuscode = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("UTMSOURCE")
  private String UTMSOURCE = null;

  @JsonProperty("UTMMEDIUM")
  private String UTMMEDIUM = null;

  @JsonProperty("UTMCAMPAIGN")
  private String UTMCAMPAIGN = null;

  @JsonProperty("UTMTERM")
  private String UTMTERM = null;

  @JsonProperty("UTMCONTENT")
  private String UTMCONTENT = null;

  @JsonProperty("CAMPAIGNID")
  private String CAMPAIGNID = null;

  @JsonProperty("ADGROUPID")
  private String ADGROUPID = null;

  @JsonProperty("ADID")
  private String ADID = null;

  @JsonProperty("MATCHTYPE")
  private String MATCHTYPE = null;

  @JsonProperty("ADPOSITION")
  private String ADPOSITION = null;

  @JsonProperty("NETWORK")
  private String NETWORK = null;

  @JsonProperty("DEVICE")
  private String DEVICE = null;

  @JsonProperty("PLACEMENT")
  private String PLACEMENT = null;

  public RestIdgardBody bonuscode(String bonuscode) {
    this.bonuscode = bonuscode;
    return this;
  }

   /**
   * Get bonuscode
   * @return bonuscode
  **/
  @Schema(description = "")
  public String getBonuscode() {
    return bonuscode;
  }

  public void setBonuscode(String bonuscode) {
    this.bonuscode = bonuscode;
  }

  public RestIdgardBody language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public RestIdgardBody UTMSOURCE(String UTMSOURCE) {
    this.UTMSOURCE = UTMSOURCE;
    return this;
  }

   /**
   * Get UTMSOURCE
   * @return UTMSOURCE
  **/
  @Schema(description = "")
  public String getUTMSOURCE() {
    return UTMSOURCE;
  }

  public void setUTMSOURCE(String UTMSOURCE) {
    this.UTMSOURCE = UTMSOURCE;
  }

  public RestIdgardBody UTMMEDIUM(String UTMMEDIUM) {
    this.UTMMEDIUM = UTMMEDIUM;
    return this;
  }

   /**
   * Get UTMMEDIUM
   * @return UTMMEDIUM
  **/
  @Schema(description = "")
  public String getUTMMEDIUM() {
    return UTMMEDIUM;
  }

  public void setUTMMEDIUM(String UTMMEDIUM) {
    this.UTMMEDIUM = UTMMEDIUM;
  }

  public RestIdgardBody UTMCAMPAIGN(String UTMCAMPAIGN) {
    this.UTMCAMPAIGN = UTMCAMPAIGN;
    return this;
  }

   /**
   * Get UTMCAMPAIGN
   * @return UTMCAMPAIGN
  **/
  @Schema(description = "")
  public String getUTMCAMPAIGN() {
    return UTMCAMPAIGN;
  }

  public void setUTMCAMPAIGN(String UTMCAMPAIGN) {
    this.UTMCAMPAIGN = UTMCAMPAIGN;
  }

  public RestIdgardBody UTMTERM(String UTMTERM) {
    this.UTMTERM = UTMTERM;
    return this;
  }

   /**
   * Get UTMTERM
   * @return UTMTERM
  **/
  @Schema(description = "")
  public String getUTMTERM() {
    return UTMTERM;
  }

  public void setUTMTERM(String UTMTERM) {
    this.UTMTERM = UTMTERM;
  }

  public RestIdgardBody UTMCONTENT(String UTMCONTENT) {
    this.UTMCONTENT = UTMCONTENT;
    return this;
  }

   /**
   * Get UTMCONTENT
   * @return UTMCONTENT
  **/
  @Schema(description = "")
  public String getUTMCONTENT() {
    return UTMCONTENT;
  }

  public void setUTMCONTENT(String UTMCONTENT) {
    this.UTMCONTENT = UTMCONTENT;
  }

  public RestIdgardBody CAMPAIGNID(String CAMPAIGNID) {
    this.CAMPAIGNID = CAMPAIGNID;
    return this;
  }

   /**
   * Get CAMPAIGNID
   * @return CAMPAIGNID
  **/
  @Schema(description = "")
  public String getCAMPAIGNID() {
    return CAMPAIGNID;
  }

  public void setCAMPAIGNID(String CAMPAIGNID) {
    this.CAMPAIGNID = CAMPAIGNID;
  }

  public RestIdgardBody ADGROUPID(String ADGROUPID) {
    this.ADGROUPID = ADGROUPID;
    return this;
  }

   /**
   * Get ADGROUPID
   * @return ADGROUPID
  **/
  @Schema(description = "")
  public String getADGROUPID() {
    return ADGROUPID;
  }

  public void setADGROUPID(String ADGROUPID) {
    this.ADGROUPID = ADGROUPID;
  }

  public RestIdgardBody ADID(String ADID) {
    this.ADID = ADID;
    return this;
  }

   /**
   * Get ADID
   * @return ADID
  **/
  @Schema(description = "")
  public String getADID() {
    return ADID;
  }

  public void setADID(String ADID) {
    this.ADID = ADID;
  }

  public RestIdgardBody MATCHTYPE(String MATCHTYPE) {
    this.MATCHTYPE = MATCHTYPE;
    return this;
  }

   /**
   * Get MATCHTYPE
   * @return MATCHTYPE
  **/
  @Schema(description = "")
  public String getMATCHTYPE() {
    return MATCHTYPE;
  }

  public void setMATCHTYPE(String MATCHTYPE) {
    this.MATCHTYPE = MATCHTYPE;
  }

  public RestIdgardBody ADPOSITION(String ADPOSITION) {
    this.ADPOSITION = ADPOSITION;
    return this;
  }

   /**
   * Get ADPOSITION
   * @return ADPOSITION
  **/
  @Schema(description = "")
  public String getADPOSITION() {
    return ADPOSITION;
  }

  public void setADPOSITION(String ADPOSITION) {
    this.ADPOSITION = ADPOSITION;
  }

  public RestIdgardBody NETWORK(String NETWORK) {
    this.NETWORK = NETWORK;
    return this;
  }

   /**
   * Get NETWORK
   * @return NETWORK
  **/
  @Schema(description = "")
  public String getNETWORK() {
    return NETWORK;
  }

  public void setNETWORK(String NETWORK) {
    this.NETWORK = NETWORK;
  }

  public RestIdgardBody DEVICE(String DEVICE) {
    this.DEVICE = DEVICE;
    return this;
  }

   /**
   * Get DEVICE
   * @return DEVICE
  **/
  @Schema(description = "")
  public String getDEVICE() {
    return DEVICE;
  }

  public void setDEVICE(String DEVICE) {
    this.DEVICE = DEVICE;
  }

  public RestIdgardBody PLACEMENT(String PLACEMENT) {
    this.PLACEMENT = PLACEMENT;
    return this;
  }

   /**
   * Get PLACEMENT
   * @return PLACEMENT
  **/
  @Schema(description = "")
  public String getPLACEMENT() {
    return PLACEMENT;
  }

  public void setPLACEMENT(String PLACEMENT) {
    this.PLACEMENT = PLACEMENT;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestIdgardBody restIdgardBody = (RestIdgardBody) o;
    return Objects.equals(this.bonuscode, restIdgardBody.bonuscode) &&
        Objects.equals(this.language, restIdgardBody.language) &&
        Objects.equals(this.UTMSOURCE, restIdgardBody.UTMSOURCE) &&
        Objects.equals(this.UTMMEDIUM, restIdgardBody.UTMMEDIUM) &&
        Objects.equals(this.UTMCAMPAIGN, restIdgardBody.UTMCAMPAIGN) &&
        Objects.equals(this.UTMTERM, restIdgardBody.UTMTERM) &&
        Objects.equals(this.UTMCONTENT, restIdgardBody.UTMCONTENT) &&
        Objects.equals(this.CAMPAIGNID, restIdgardBody.CAMPAIGNID) &&
        Objects.equals(this.ADGROUPID, restIdgardBody.ADGROUPID) &&
        Objects.equals(this.ADID, restIdgardBody.ADID) &&
        Objects.equals(this.MATCHTYPE, restIdgardBody.MATCHTYPE) &&
        Objects.equals(this.ADPOSITION, restIdgardBody.ADPOSITION) &&
        Objects.equals(this.NETWORK, restIdgardBody.NETWORK) &&
        Objects.equals(this.DEVICE, restIdgardBody.DEVICE) &&
        Objects.equals(this.PLACEMENT, restIdgardBody.PLACEMENT);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bonuscode, language, UTMSOURCE, UTMMEDIUM, UTMCAMPAIGN, UTMTERM, UTMCONTENT, CAMPAIGNID, ADGROUPID, ADID, MATCHTYPE, ADPOSITION, NETWORK, DEVICE, PLACEMENT);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestIdgardBody {\n");
    
    sb.append("    bonuscode: ").append(toIndentedString(bonuscode)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    UTMSOURCE: ").append(toIndentedString(UTMSOURCE)).append("\n");
    sb.append("    UTMMEDIUM: ").append(toIndentedString(UTMMEDIUM)).append("\n");
    sb.append("    UTMCAMPAIGN: ").append(toIndentedString(UTMCAMPAIGN)).append("\n");
    sb.append("    UTMTERM: ").append(toIndentedString(UTMTERM)).append("\n");
    sb.append("    UTMCONTENT: ").append(toIndentedString(UTMCONTENT)).append("\n");
    sb.append("    CAMPAIGNID: ").append(toIndentedString(CAMPAIGNID)).append("\n");
    sb.append("    ADGROUPID: ").append(toIndentedString(ADGROUPID)).append("\n");
    sb.append("    ADID: ").append(toIndentedString(ADID)).append("\n");
    sb.append("    MATCHTYPE: ").append(toIndentedString(MATCHTYPE)).append("\n");
    sb.append("    ADPOSITION: ").append(toIndentedString(ADPOSITION)).append("\n");
    sb.append("    NETWORK: ").append(toIndentedString(NETWORK)).append("\n");
    sb.append("    DEVICE: ").append(toIndentedString(DEVICE)).append("\n");
    sb.append("    PLACEMENT: ").append(toIndentedString(PLACEMENT)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
