/*
 * iDGARD UIAPI
 * This API is intended for internal usage only. No guarantees regarding completeness of documentation and API stability are given.  Swagger UI available at: <a href=\"/assets/idgapi/doc/index.html\">&lt;server&gt;/assets/idgapi/doc/index.html</a>  Redoc not available due to API size 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.idgard.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SimpleUserInfo
 */



public class SimpleUserInfo {
  @JsonProperty("csfrToken")
  private String csfrToken = null;

  @JsonProperty("lastLogin")
  private Long lastLogin = null;

  @JsonProperty("nick")
  private String nick = null;

  /**
   * Gets or Sets userType
   */
  public enum UserTypeEnum {
    ADMIN("ADMIN"),
    FULL_LICENSE("FULL_LICENSE"),
    GUEST_LICENSE("GUEST_LICENSE"),
    ANONYMOUS("ANONYMOUS");

    private String value;

    UserTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static UserTypeEnum fromValue(String input) {
      for (UserTypeEnum b : UserTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("userType")
  private UserTypeEnum userType = null;

  public SimpleUserInfo csfrToken(String csfrToken) {
    this.csfrToken = csfrToken;
    return this;
  }

   /**
   * Get csfrToken
   * @return csfrToken
  **/
  @Schema(description = "")
  public String getCsfrToken() {
    return csfrToken;
  }

  public void setCsfrToken(String csfrToken) {
    this.csfrToken = csfrToken;
  }

  public SimpleUserInfo lastLogin(Long lastLogin) {
    this.lastLogin = lastLogin;
    return this;
  }

   /**
   * Get lastLogin
   * @return lastLogin
  **/
  @Schema(description = "")
  public Long getLastLogin() {
    return lastLogin;
  }

  public void setLastLogin(Long lastLogin) {
    this.lastLogin = lastLogin;
  }

  public SimpleUserInfo nick(String nick) {
    this.nick = nick;
    return this;
  }

   /**
   * Get nick
   * @return nick
  **/
  @Schema(description = "")
  public String getNick() {
    return nick;
  }

  public void setNick(String nick) {
    this.nick = nick;
  }

  public SimpleUserInfo userType(UserTypeEnum userType) {
    this.userType = userType;
    return this;
  }

   /**
   * Get userType
   * @return userType
  **/
  @Schema(description = "")
  public UserTypeEnum getUserType() {
    return userType;
  }

  public void setUserType(UserTypeEnum userType) {
    this.userType = userType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimpleUserInfo simpleUserInfo = (SimpleUserInfo) o;
    return Objects.equals(this.csfrToken, simpleUserInfo.csfrToken) &&
        Objects.equals(this.lastLogin, simpleUserInfo.lastLogin) &&
        Objects.equals(this.nick, simpleUserInfo.nick) &&
        Objects.equals(this.userType, simpleUserInfo.userType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csfrToken, lastLogin, nick, userType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleUserInfo {\n");
    
    sb.append("    csfrToken: ").append(toIndentedString(csfrToken)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    nick: ").append(toIndentedString(nick)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
