/*
 * DeepBox
 * DeepBox API Documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: info@deepcloud.swiss
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.deepbox.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DeepBoxAdd
 */



public class DeepBoxAdd {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("companyId")
  private String companyId = null;

  @JsonProperty("createInitialBox")
  private Boolean createInitialBox = null;

  public DeepBoxAdd name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DeepBoxAdd companyId(String companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  @Schema(required = true, description = "")
  public String getCompanyId() {
    return companyId;
  }

  public void setCompanyId(String companyId) {
    this.companyId = companyId;
  }

  public DeepBoxAdd createInitialBox(Boolean createInitialBox) {
    this.createInitialBox = createInitialBox;
    return this;
  }

   /**
   * Get createInitialBox
   * @return createInitialBox
  **/
  @Schema(description = "")
  public Boolean isCreateInitialBox() {
    return createInitialBox;
  }

  public void setCreateInitialBox(Boolean createInitialBox) {
    this.createInitialBox = createInitialBox;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeepBoxAdd deepBoxAdd = (DeepBoxAdd) o;
    return Objects.equals(this.name, deepBoxAdd.name) &&
        Objects.equals(this.companyId, deepBoxAdd.companyId) &&
        Objects.equals(this.createInitialBox, deepBoxAdd.createInitialBox);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, companyId, createInitialBox);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeepBoxAdd {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    createInitialBox: ").append(toIndentedString(createInitialBox)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
