/*
 * DeepAdmin API
 * General API for DeepCloud Admin / Subscription Service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@deepcloud.swiss
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.deepcloud.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets VerificationStateEnum
 */
public enum VerificationStateEnum {
  STRONG("strong"),
  WEAK("weak"),
  NONE("none");

  private String value;

  VerificationStateEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static VerificationStateEnum fromValue(String input) {
    for (VerificationStateEnum b : VerificationStateEnum.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
