/*
 * Secure Data Space API
 * Version 4.1.2 - built at: 2017-03-02 18:50:25, API server: https://sds.ssp-europe.eu/api/v4
 *
 * OpenAPI spec version: 4.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * CreateActiveDirectoryConfigRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-21T19:15:03.115+01:00")
public class CreateActiveDirectoryConfigRequest {
  @JsonProperty("alias")
  private String alias = null;

  @JsonProperty("serverIp")
  private String serverIp = null;

  @JsonProperty("serverPort")
  private Integer serverPort = null;

  @JsonProperty("serverAdminName")
  private String serverAdminName = null;

  @JsonProperty("serverAdminPassword")
  private String serverAdminPassword = null;

  @JsonProperty("ldapUsersDomain")
  private String ldapUsersDomain = null;

  @JsonProperty("userFilter")
  private String userFilter = null;

  @JsonProperty("userImport")
  private Boolean userImport = null;

  @JsonProperty("adExportGroup")
  private String adExportGroup = null;

  @JsonProperty("importExpireAt")
  private Date importExpireAt = null;

  @JsonProperty("sdsImportGroup")
  private Long sdsImportGroup = null;

  @JsonProperty("createHomeFolder")
  private Boolean createHomeFolder = null;

  @JsonProperty("homeFolderParent")
  private Long homeFolderParent = null;

  @JsonProperty("useLdaps")
  private Boolean useLdaps = null;

  @JsonProperty("sslFingerPrint")
  private String sslFingerPrint = null;

  public CreateActiveDirectoryConfigRequest alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Alias string
   * @return alias
  **/
  @ApiModelProperty(example = "null", required = true, value = "Alias string")
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public CreateActiveDirectoryConfigRequest serverIp(String serverIp) {
    this.serverIp = serverIp;
    return this;
  }

   /**
   * IPv4 or IPv6 address or host name
   * @return serverIp
  **/
  @ApiModelProperty(example = "null", required = true, value = "IPv4 or IPv6 address or host name")
  public String getServerIp() {
    return serverIp;
  }

  public void setServerIp(String serverIp) {
    this.serverIp = serverIp;
  }

  public CreateActiveDirectoryConfigRequest serverPort(Integer serverPort) {
    this.serverPort = serverPort;
    return this;
  }

   /**
   * Port
   * @return serverPort
  **/
  @ApiModelProperty(example = "null", required = true, value = "Port")
  public Integer getServerPort() {
    return serverPort;
  }

  public void setServerPort(Integer serverPort) {
    this.serverPort = serverPort;
  }

  public CreateActiveDirectoryConfigRequest serverAdminName(String serverAdminName) {
    this.serverAdminName = serverAdminName;
    return this;
  }

   /**
   * DistinguishedName of Active Directory administrative account
   * @return serverAdminName
  **/
  @ApiModelProperty(example = "null", required = true, value = "DistinguishedName of Active Directory administrative account")
  public String getServerAdminName() {
    return serverAdminName;
  }

  public void setServerAdminName(String serverAdminName) {
    this.serverAdminName = serverAdminName;
  }

  public CreateActiveDirectoryConfigRequest serverAdminPassword(String serverAdminPassword) {
    this.serverAdminPassword = serverAdminPassword;
    return this;
  }

   /**
   * Password of Active Directory administrative account
   * @return serverAdminPassword
  **/
  @ApiModelProperty(example = "null", required = true, value = "Password of Active Directory administrative account")
  public String getServerAdminPassword() {
    return serverAdminPassword;
  }

  public void setServerAdminPassword(String serverAdminPassword) {
    this.serverAdminPassword = serverAdminPassword;
  }

  public CreateActiveDirectoryConfigRequest ldapUsersDomain(String ldapUsersDomain) {
    this.ldapUsersDomain = ldapUsersDomain;
    return this;
  }

   /**
   * Search scope of Active Directory; only users below this node can log on.
   * @return ldapUsersDomain
  **/
  @ApiModelProperty(example = "null", required = true, value = "Search scope of Active Directory; only users below this node can log on.")
  public String getLdapUsersDomain() {
    return ldapUsersDomain;
  }

  public void setLdapUsersDomain(String ldapUsersDomain) {
    this.ldapUsersDomain = ldapUsersDomain;
  }

  public CreateActiveDirectoryConfigRequest userFilter(String userFilter) {
    this.userFilter = userFilter;
    return this;
  }

   /**
   * Name of Active Directory attribute that is used as login name
   * @return userFilter
  **/
  @ApiModelProperty(example = "null", required = true, value = "Name of Active Directory attribute that is used as login name")
  public String getUserFilter() {
    return userFilter;
  }

  public void setUserFilter(String userFilter) {
    this.userFilter = userFilter;
  }

  public CreateActiveDirectoryConfigRequest userImport(Boolean userImport) {
    this.userImport = userImport;
    return this;
  }

   /**
   * Determines if an SDS account is automatically created for a new user who successfully logs on with his/her AD account,
   * @return userImport
  **/
  @ApiModelProperty(example = "null", required = true, value = "Determines if an SDS account is automatically created for a new user who successfully logs on with his/her AD account,")
  public Boolean getUserImport() {
    return userImport;
  }

  public void setUserImport(Boolean userImport) {
    this.userImport = userImport;
  }

  public CreateActiveDirectoryConfigRequest adExportGroup(String adExportGroup) {
    this.adExportGroup = adExportGroup;
    return this;
  }

   /**
   * If ad_userimport is set to true, a user must be member of this Active Directory group to receive a newly created SDS account.
   * @return adExportGroup
  **/
  @ApiModelProperty(example = "null", value = "If ad_userimport is set to true, a user must be member of this Active Directory group to receive a newly created SDS account.")
  public String getAdExportGroup() {
    return adExportGroup;
  }

  public void setAdExportGroup(String adExportGroup) {
    this.adExportGroup = adExportGroup;
  }

  public CreateActiveDirectoryConfigRequest importExpireAt(Date importExpireAt) {
    this.importExpireAt = importExpireAt;
    return this;
  }

   /**
   * Default expiration date of users who are created by automatic import.
   * @return importExpireAt
  **/
  @ApiModelProperty(example = "null", value = "Default expiration date of users who are created by automatic import.")
  public Date getImportExpireAt() {
    return importExpireAt;
  }

  public void setImportExpireAt(Date importExpireAt) {
    this.importExpireAt = importExpireAt;
  }

  public CreateActiveDirectoryConfigRequest sdsImportGroup(Long sdsImportGroup) {
    this.sdsImportGroup = sdsImportGroup;
    return this;
  }

   /**
   * User group that is assigned to users who are created by automatic import.
   * @return sdsImportGroup
  **/
  @ApiModelProperty(example = "null", value = "User group that is assigned to users who are created by automatic import.")
  public Long getSdsImportGroup() {
    return sdsImportGroup;
  }

  public void setSdsImportGroup(Long sdsImportGroup) {
    this.sdsImportGroup = sdsImportGroup;
  }

  public CreateActiveDirectoryConfigRequest createHomeFolder(Boolean createHomeFolder) {
    this.createHomeFolder = createHomeFolder;
    return this;
  }

   /**
   * Determines whether a room is created for each user that is created by automatic import (Like a home folder). The room's name will equal the user's login name.
   * @return createHomeFolder
  **/
  @ApiModelProperty(example = "null", value = "Determines whether a room is created for each user that is created by automatic import (Like a home folder). The room's name will equal the user's login name.")
  public Boolean getCreateHomeFolder() {
    return createHomeFolder;
  }

  public void setCreateHomeFolder(Boolean createHomeFolder) {
    this.createHomeFolder = createHomeFolder;
  }

  public CreateActiveDirectoryConfigRequest homeFolderParent(Long homeFolderParent) {
    this.homeFolderParent = homeFolderParent;
    return this;
  }

   /**
   * ID of the Data Room in which the individual rooms for users will be created (cf. 'ad_create_home_folder_on').
   * @return homeFolderParent
  **/
  @ApiModelProperty(example = "null", value = "ID of the Data Room in which the individual rooms for users will be created (cf. 'ad_create_home_folder_on').")
  public Long getHomeFolderParent() {
    return homeFolderParent;
  }

  public void setHomeFolderParent(Long homeFolderParent) {
    this.homeFolderParent = homeFolderParent;
  }

  public CreateActiveDirectoryConfigRequest useLdaps(Boolean useLdaps) {
    this.useLdaps = useLdaps;
    return this;
  }

   /**
   * Determines whether LDAPS should be used instead of plain LDAP.
   * @return useLdaps
  **/
  @ApiModelProperty(example = "null", required = true, value = "Determines whether LDAPS should be used instead of plain LDAP.")
  public Boolean getUseLdaps() {
    return useLdaps;
  }

  public void setUseLdaps(Boolean useLdaps) {
    this.useLdaps = useLdaps;
  }

  public CreateActiveDirectoryConfigRequest sslFingerPrint(String sslFingerPrint) {
    this.sslFingerPrint = sslFingerPrint;
    return this;
  }

   /**
   * SSL finger print of Active Directory server.  Mandatory for LDAPS connections. Format: <Algorithm>/<FingerPrint>
   * @return sslFingerPrint
  **/
  @ApiModelProperty(example = "null", value = "SSL finger print of Active Directory server.  Mandatory for LDAPS connections. Format: <Algorithm>/<FingerPrint>")
  public String getSslFingerPrint() {
    return sslFingerPrint;
  }

  public void setSslFingerPrint(String sslFingerPrint) {
    this.sslFingerPrint = sslFingerPrint;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateActiveDirectoryConfigRequest createActiveDirectoryConfigRequest = (CreateActiveDirectoryConfigRequest) o;
    return Objects.equals(this.alias, createActiveDirectoryConfigRequest.alias) &&
        Objects.equals(this.serverIp, createActiveDirectoryConfigRequest.serverIp) &&
        Objects.equals(this.serverPort, createActiveDirectoryConfigRequest.serverPort) &&
        Objects.equals(this.serverAdminName, createActiveDirectoryConfigRequest.serverAdminName) &&
        Objects.equals(this.serverAdminPassword, createActiveDirectoryConfigRequest.serverAdminPassword) &&
        Objects.equals(this.ldapUsersDomain, createActiveDirectoryConfigRequest.ldapUsersDomain) &&
        Objects.equals(this.userFilter, createActiveDirectoryConfigRequest.userFilter) &&
        Objects.equals(this.userImport, createActiveDirectoryConfigRequest.userImport) &&
        Objects.equals(this.adExportGroup, createActiveDirectoryConfigRequest.adExportGroup) &&
        Objects.equals(this.importExpireAt, createActiveDirectoryConfigRequest.importExpireAt) &&
        Objects.equals(this.sdsImportGroup, createActiveDirectoryConfigRequest.sdsImportGroup) &&
        Objects.equals(this.createHomeFolder, createActiveDirectoryConfigRequest.createHomeFolder) &&
        Objects.equals(this.homeFolderParent, createActiveDirectoryConfigRequest.homeFolderParent) &&
        Objects.equals(this.useLdaps, createActiveDirectoryConfigRequest.useLdaps) &&
        Objects.equals(this.sslFingerPrint, createActiveDirectoryConfigRequest.sslFingerPrint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alias, serverIp, serverPort, serverAdminName, serverAdminPassword, ldapUsersDomain, userFilter, userImport, adExportGroup, importExpireAt, sdsImportGroup, createHomeFolder, homeFolderParent, useLdaps, sslFingerPrint);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateActiveDirectoryConfigRequest {\n");
    
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    serverIp: ").append(toIndentedString(serverIp)).append("\n");
    sb.append("    serverPort: ").append(toIndentedString(serverPort)).append("\n");
    sb.append("    serverAdminName: ").append(toIndentedString(serverAdminName)).append("\n");
    sb.append("    serverAdminPassword: ").append(toIndentedString(serverAdminPassword)).append("\n");
    sb.append("    ldapUsersDomain: ").append(toIndentedString(ldapUsersDomain)).append("\n");
    sb.append("    userFilter: ").append(toIndentedString(userFilter)).append("\n");
    sb.append("    userImport: ").append(toIndentedString(userImport)).append("\n");
    sb.append("    adExportGroup: ").append(toIndentedString(adExportGroup)).append("\n");
    sb.append("    importExpireAt: ").append(toIndentedString(importExpireAt)).append("\n");
    sb.append("    sdsImportGroup: ").append(toIndentedString(sdsImportGroup)).append("\n");
    sb.append("    createHomeFolder: ").append(toIndentedString(createHomeFolder)).append("\n");
    sb.append("    homeFolderParent: ").append(toIndentedString(homeFolderParent)).append("\n");
    sb.append("    useLdaps: ").append(toIndentedString(useLdaps)).append("\n");
    sb.append("    sslFingerPrint: ").append(toIndentedString(sslFingerPrint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

