/*
 * Secure Data Space API
 * Version 4.1.2 - built at: 2017-03-02 18:50:25, API server: https://sds.ssp-europe.eu/api/v4
 *
 * OpenAPI spec version: 4.1.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CreateRoomRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-21T19:15:03.115+01:00")
public class CreateRoomRequest {
  @JsonProperty("parentId")
  private Long parentId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("hasRecycleBin")
  private Boolean hasRecycleBin = null;

  @JsonProperty("recycleBinRetentionPeriod")
  private Integer recycleBinRetentionPeriod = null;

  @JsonProperty("quota")
  private Long quota = null;

  @JsonProperty("inheritPermissions")
  private Boolean inheritPermissions = null;

  @JsonProperty("adminIds")
  private List<Long> adminIds = new ArrayList<Long>();

  @JsonProperty("adminGroupIds")
  private List<Long> adminGroupIds = new ArrayList<Long>();

  @JsonProperty("newGroupMemberAcceptance")
  private String newGroupMemberAcceptance = null;

  @JsonProperty("notes")
  private String notes = null;

  public CreateRoomRequest parentId(Long parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Parent Room Id or null to create a top-level room
   * @return parentId
  **/
  @ApiModelProperty(example = "null", value = "Parent Room Id or null to create a top-level room")
  public Long getParentId() {
    return parentId;
  }

  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }

  public CreateRoomRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateRoomRequest hasRecycleBin(Boolean hasRecycleBin) {
    this.hasRecycleBin = hasRecycleBin;
    return this;
  }

   /**
   * Activate Recycle Bin
   * @return hasRecycleBin
  **/
  @ApiModelProperty(example = "null", value = "Activate Recycle Bin")
  public Boolean getHasRecycleBin() {
    return hasRecycleBin;
  }

  public void setHasRecycleBin(Boolean hasRecycleBin) {
    this.hasRecycleBin = hasRecycleBin;
  }

  public CreateRoomRequest recycleBinRetentionPeriod(Integer recycleBinRetentionPeriod) {
    this.recycleBinRetentionPeriod = recycleBinRetentionPeriod;
    return this;
  }

   /**
   * Retention period for deleted nodes in days. Integer between 0 and 9999.
   * @return recycleBinRetentionPeriod
  **/
  @ApiModelProperty(example = "null", value = "Retention period for deleted nodes in days. Integer between 0 and 9999.")
  public Integer getRecycleBinRetentionPeriod() {
    return recycleBinRetentionPeriod;
  }

  public void setRecycleBinRetentionPeriod(Integer recycleBinRetentionPeriod) {
    this.recycleBinRetentionPeriod = recycleBinRetentionPeriod;
  }

  public CreateRoomRequest quota(Long quota) {
    this.quota = quota;
    return this;
  }

   /**
   * Quota in Byte
   * @return quota
  **/
  @ApiModelProperty(example = "null", value = "Quota in Byte")
  public Long getQuota() {
    return quota;
  }

  public void setQuota(Long quota) {
    this.quota = quota;
  }

  public CreateRoomRequest inheritPermissions(Boolean inheritPermissions) {
    this.inheritPermissions = inheritPermissions;
    return this;
  }

   /**
   * Inherit permissions from parent room.
   * @return inheritPermissions
  **/
  @ApiModelProperty(example = "null", value = "Inherit permissions from parent room.")
  public Boolean getInheritPermissions() {
    return inheritPermissions;
  }

  public void setInheritPermissions(Boolean inheritPermissions) {
    this.inheritPermissions = inheritPermissions;
  }

  public CreateRoomRequest adminIds(List<Long> adminIds) {
    this.adminIds = adminIds;
    return this;
  }

  public CreateRoomRequest addAdminIdsItem(Long adminIdsItem) {
    this.adminIds.add(adminIdsItem);
    return this;
  }

   /**
   * List of user Ids. A room requires at least one admin (user or group)
   * @return adminIds
  **/
  @ApiModelProperty(example = "null", value = "List of user Ids. A room requires at least one admin (user or group)")
  public List<Long> getAdminIds() {
    return adminIds;
  }

  public void setAdminIds(List<Long> adminIds) {
    this.adminIds = adminIds;
  }

  public CreateRoomRequest adminGroupIds(List<Long> adminGroupIds) {
    this.adminGroupIds = adminGroupIds;
    return this;
  }

  public CreateRoomRequest addAdminGroupIdsItem(Long adminGroupIdsItem) {
    this.adminGroupIds.add(adminGroupIdsItem);
    return this;
  }

   /**
   * List of group Ids. A room requires at least one admin (user or group)
   * @return adminGroupIds
  **/
  @ApiModelProperty(example = "null", value = "List of group Ids. A room requires at least one admin (user or group)")
  public List<Long> getAdminGroupIds() {
    return adminGroupIds;
  }

  public void setAdminGroupIds(List<Long> adminGroupIds) {
    this.adminGroupIds = adminGroupIds;
  }

  public CreateRoomRequest newGroupMemberAcceptance(String newGroupMemberAcceptance) {
    this.newGroupMemberAcceptance = newGroupMemberAcceptance;
    return this;
  }

   /**
   * autoallow|pending; default:autoallow. Only relevant if adminGroupIds has items
   * @return newGroupMemberAcceptance
  **/
  @ApiModelProperty(example = "null", value = "autoallow|pending; default:autoallow. Only relevant if adminGroupIds has items")
  public String getNewGroupMemberAcceptance() {
    return newGroupMemberAcceptance;
  }

  public void setNewGroupMemberAcceptance(String newGroupMemberAcceptance) {
    this.newGroupMemberAcceptance = newGroupMemberAcceptance;
  }

  public CreateRoomRequest notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * User notes
   * @return notes
  **/
  @ApiModelProperty(example = "null", value = "User notes")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRoomRequest createRoomRequest = (CreateRoomRequest) o;
    return Objects.equals(this.parentId, createRoomRequest.parentId) &&
        Objects.equals(this.name, createRoomRequest.name) &&
        Objects.equals(this.hasRecycleBin, createRoomRequest.hasRecycleBin) &&
        Objects.equals(this.recycleBinRetentionPeriod, createRoomRequest.recycleBinRetentionPeriod) &&
        Objects.equals(this.quota, createRoomRequest.quota) &&
        Objects.equals(this.inheritPermissions, createRoomRequest.inheritPermissions) &&
        Objects.equals(this.adminIds, createRoomRequest.adminIds) &&
        Objects.equals(this.adminGroupIds, createRoomRequest.adminGroupIds) &&
        Objects.equals(this.newGroupMemberAcceptance, createRoomRequest.newGroupMemberAcceptance) &&
        Objects.equals(this.notes, createRoomRequest.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parentId, name, hasRecycleBin, recycleBinRetentionPeriod, quota, inheritPermissions, adminIds, adminGroupIds, newGroupMemberAcceptance, notes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRoomRequest {\n");
    
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    hasRecycleBin: ").append(toIndentedString(hasRecycleBin)).append("\n");
    sb.append("    recycleBinRetentionPeriod: ").append(toIndentedString(recycleBinRetentionPeriod)).append("\n");
    sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
    sb.append("    inheritPermissions: ").append(toIndentedString(inheritPermissions)).append("\n");
    sb.append("    adminIds: ").append(toIndentedString(adminIds)).append("\n");
    sb.append("    adminGroupIds: ").append(toIndentedString(adminGroupIds)).append("\n");
    sb.append("    newGroupMemberAcceptance: ").append(toIndentedString(newGroupMemberAcceptance)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

