/*
 * Files.com API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@files.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.brick.io.swagger.client.api;

import ch.cyberduck.core.brick.io.swagger.client.ApiException;
import ch.cyberduck.core.brick.io.swagger.client.model.SsoStrategyEntity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SsoStrategiesApi
 */
@Ignore
public class SsoStrategiesApiTest {

    private final SsoStrategiesApi api = new SsoStrategiesApi();

    
    /**
     * List Sso Strategies
     *
     * List Sso Strategies
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSsoStrategiesTest() throws ApiException {
        String cursor = null;
        Integer perPage = null;
        List<SsoStrategyEntity> response = api.getSsoStrategies(cursor, perPage);

        // TODO: test validations
    }
    
    /**
     * Show Sso Strategy
     *
     * Show Sso Strategy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSsoStrategiesIdTest() throws ApiException {
        Integer id = null;
        SsoStrategyEntity response = api.getSsoStrategiesId(id);

        // TODO: test validations
    }
    
}
