/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.box.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * The operation to perform on the classification metadata template instance. In this case, it use used to replace the value stored for the &#x60;Box__Security__Classification__Key&#x60; field with a new value.
 */
@Schema(description = "The operation to perform on the classification metadata template instance. In this case, it use used to replace the value stored for the `Box__Security__Classification__Key` field with a new value.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-25T11:35:18.602705+01:00[Europe/Zurich]")
public class Body19 {
  /**
   * &#x60;replace&#x60;
   */
  public enum OpEnum {
    REPLACE("replace");

    private String value;

    OpEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static OpEnum fromValue(String text) {
      for (OpEnum b : OpEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("op")
  private OpEnum op = null;

  /**
   * &#x60;/Box__Security__Classification__Key&#x60;
   */
  public enum PathEnum {
    KEY("/Box__Security__Classification__Key");

    private String value;

    PathEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PathEnum fromValue(String text) {
      for (PathEnum b : PathEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("path")
  private PathEnum path = null;

  @JsonProperty("value")
  private String value = null;

  public Body19 op(OpEnum op) {
    this.op = op;
    return this;
  }

   /**
   * &#x60;replace&#x60;
   * @return op
  **/
  @Schema(example = "replace", description = "`replace`")
  public OpEnum getOp() {
    return op;
  }

  public void setOp(OpEnum op) {
    this.op = op;
  }

  public Body19 path(PathEnum path) {
    this.path = path;
    return this;
  }

   /**
   * &#x60;/Box__Security__Classification__Key&#x60;
   * @return path
  **/
  @Schema(example = "/Box__Security__Classification__Key", description = "`/Box__Security__Classification__Key`")
  public PathEnum getPath() {
    return path;
  }

  public void setPath(PathEnum path) {
    this.path = path;
  }

  public Body19 value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The name of the classification to apply to this folder.  To list the available classifications in an enterprise, use the classification API to retrieve the [classification template](e://get_metadata_templates_enterprise_securityClassification-6VMVochwUWo_schema) which lists all available classification keys.
   * @return value
  **/
  @Schema(example = "Sensitive", description = "The name of the classification to apply to this folder.  To list the available classifications in an enterprise, use the classification API to retrieve the [classification template](e://get_metadata_templates_enterprise_securityClassification-6VMVochwUWo_schema) which lists all available classification keys.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body19 body19 = (Body19) o;
    return Objects.equals(this.op, body19.op) &&
        Objects.equals(this.path, body19.path) &&
        Objects.equals(this.value, body19.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(op, path, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body19 {\n");
    
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
