/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.box.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * An instance of the classification metadata template, containing the classification applied to the file or folder.  To get more details about the classification applied to an item, request the classification metadata template.
 */
@Schema(description = "An instance of the classification metadata template, containing the classification applied to the file or folder.  To get more details about the classification applied to an item, request the classification metadata template.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-25T11:35:18.602705+01:00[Europe/Zurich]")
public class Classification {
  @JsonProperty("Box__Security__Classification__Key")
  private String boxSecurityClassificationKey = null;

  @JsonProperty("$parent")
  private String $parent = null;

  /**
   * &#x60;securityClassification-6VMVochwUWo&#x60;
   */
  public enum TemplateEnum {
    _6VMVOCHWUWO("securityClassification-6VMVochwUWo");

    private String value;

    TemplateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TemplateEnum fromValue(String text) {
      for (TemplateEnum b : TemplateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("$template")
  private TemplateEnum $template = null;

  @JsonProperty("$scope")
  private String $scope = null;

  @JsonProperty("$version")
  private Integer $version = null;

  @JsonProperty("$type")
  private String $type = null;

  @JsonProperty("$typeVersion")
  private BigDecimal $typeVersion = null;

  @JsonProperty("$canEdit")
  private Boolean $canEdit = null;

  public Classification boxSecurityClassificationKey(String boxSecurityClassificationKey) {
    this.boxSecurityClassificationKey = boxSecurityClassificationKey;
    return this;
  }

   /**
   * The name of the classification applied to the item.
   * @return boxSecurityClassificationKey
  **/
  @Schema(example = "Sensitive", description = "The name of the classification applied to the item.")
  public String getBoxSecurityClassificationKey() {
    return boxSecurityClassificationKey;
  }

  public void setBoxSecurityClassificationKey(String boxSecurityClassificationKey) {
    this.boxSecurityClassificationKey = boxSecurityClassificationKey;
  }

  public Classification $parent(String $parent) {
    this.$parent = $parent;
    return this;
  }

   /**
   * The identifier of the item that this metadata instance has been attached to. This combines the &#x60;type&#x60; and the &#x60;id&#x60; of the parent in the form &#x60;{type}_{id}&#x60;.
   * @return $parent
  **/
  @Schema(example = "folder_59449484661,", description = "The identifier of the item that this metadata instance has been attached to. This combines the `type` and the `id` of the parent in the form `{type}_{id}`.")
  public String get$Parent() {
    return $parent;
  }

  public void set$Parent(String $parent) {
    this.$parent = $parent;
  }

  public Classification $template(TemplateEnum $template) {
    this.$template = $template;
    return this;
  }

   /**
   * &#x60;securityClassification-6VMVochwUWo&#x60;
   * @return $template
  **/
  @Schema(example = "securityClassification-6VMVochwUWo", description = "`securityClassification-6VMVochwUWo`")
  public TemplateEnum get$Template() {
    return $template;
  }

  public void set$Template(TemplateEnum $template) {
    this.$template = $template;
  }

  public Classification $scope(String $scope) {
    this.$scope = $scope;
    return this;
  }

   /**
   * The scope of the enterprise that this classification has been applied for.  This will be in the format &#x60;enterprise_{enterprise_id}&#x60;.
   * @return $scope
  **/
  @Schema(example = "enterprise_27335", description = "The scope of the enterprise that this classification has been applied for.  This will be in the format `enterprise_{enterprise_id}`.")
  public String get$Scope() {
    return $scope;
  }

  public void set$Scope(String $scope) {
    this.$scope = $scope;
  }

  public Classification $version(Integer $version) {
    this.$version = $version;
    return this;
  }

   /**
   * The version of the metadata instance. This version starts at 0 and increases every time a classification is updated.
   * @return $version
  **/
  @Schema(example = "1", description = "The version of the metadata instance. This version starts at 0 and increases every time a classification is updated.")
  public Integer get$Version() {
    return $version;
  }

  public void set$Version(Integer $version) {
    this.$version = $version;
  }

  public Classification $type(String $type) {
    this.$type = $type;
    return this;
  }

   /**
   * The unique ID of this classification instance. This will be include the name of the classification template and a unique ID.
   * @return $type
  **/
  @Schema(example = "securityClassification-6VMVochwUWo-fd31537a-0f95-4d86-9f2b-5974a29978f8", description = "The unique ID of this classification instance. This will be include the name of the classification template and a unique ID.")
  public String get$Type() {
    return $type;
  }

  public void set$Type(String $type) {
    this.$type = $type;
  }

  public Classification $typeVersion(BigDecimal $typeVersion) {
    this.$typeVersion = $typeVersion;
    return this;
  }

   /**
   * The version of the metadata template. This version starts at 0 and increases every time the template is updated. This is mostly for internal use.
   * @return $typeVersion
  **/
  @Schema(example = "5", description = "The version of the metadata template. This version starts at 0 and increases every time the template is updated. This is mostly for internal use.")
  public BigDecimal get$TypeVersion() {
    return $typeVersion;
  }

  public void set$TypeVersion(BigDecimal $typeVersion) {
    this.$typeVersion = $typeVersion;
  }

  public Classification $canEdit(Boolean $canEdit) {
    this.$canEdit = $canEdit;
    return this;
  }

   /**
   * Whether an end user can change the classification.
   * @return $canEdit
  **/
  @Schema(example = "true", description = "Whether an end user can change the classification.")
  public Boolean is$CanEdit() {
    return $canEdit;
  }

  public void set$CanEdit(Boolean $canEdit) {
    this.$canEdit = $canEdit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Classification classification = (Classification) o;
    return Objects.equals(this.boxSecurityClassificationKey, classification.boxSecurityClassificationKey) &&
        Objects.equals(this.$parent, classification.$parent) &&
        Objects.equals(this.$template, classification.$template) &&
        Objects.equals(this.$scope, classification.$scope) &&
        Objects.equals(this.$version, classification.$version) &&
        Objects.equals(this.$type, classification.$type) &&
        Objects.equals(this.$typeVersion, classification.$typeVersion) &&
        Objects.equals(this.$canEdit, classification.$canEdit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(boxSecurityClassificationKey, $parent, $template, $scope, $version, $type, $typeVersion, $canEdit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Classification {\n");
    
    sb.append("    boxSecurityClassificationKey: ").append(toIndentedString(boxSecurityClassificationKey)).append("\n");
    sb.append("    $parent: ").append(toIndentedString($parent)).append("\n");
    sb.append("    $template: ").append(toIndentedString($template)).append("\n");
    sb.append("    $scope: ").append(toIndentedString($scope)).append("\n");
    sb.append("    $version: ").append(toIndentedString($version)).append("\n");
    sb.append("    $type: ").append(toIndentedString($type)).append("\n");
    sb.append("    $typeVersion: ").append(toIndentedString($typeVersion)).append("\n");
    sb.append("    $canEdit: ").append(toIndentedString($canEdit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
