/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.box.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * The metadata assigned to a using for Box skills.
 */
@Schema(description = "The metadata assigned to a using for Box skills.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-25T11:35:18.602705+01:00[Europe/Zurich]")
public class SkillCardsMetadata {
  @JsonProperty("$canEdit")
  private Boolean $canEdit = null;

  @JsonProperty("$id")
  private UUID $id = null;

  @JsonProperty("$parent")
  private String $parent = null;

  @JsonProperty("$scope")
  private String $scope = null;

  @JsonProperty("$template")
  private String $template = null;

  @JsonProperty("$type")
  private String $type = null;

  @JsonProperty("$typeVersion")
  private Integer $typeVersion = null;

  @JsonProperty("$version")
  private Integer $version = null;

  @JsonProperty("cards")
  private List<OneOfSkillCardsMetadataCardsItems> cards = null;

  public SkillCardsMetadata $canEdit(Boolean $canEdit) {
    this.$canEdit = $canEdit;
    return this;
  }

   /**
   * Whether the user can edit this metadata
   * @return $canEdit
  **/
  @Schema(example = "true", description = "Whether the user can edit this metadata")
  public Boolean is$CanEdit() {
    return $canEdit;
  }

  public void set$CanEdit(Boolean $canEdit) {
    this.$canEdit = $canEdit;
  }

  public SkillCardsMetadata $id(UUID $id) {
    this.$id = $id;
    return this;
  }

   /**
   * A UUID to identify the metadata object
   * @return $id
  **/
  @Schema(example = "01234500-12f1-1234-aa12-b1d234cb567e", description = "A UUID to identify the metadata object")
  public UUID get$Id() {
    return $id;
  }

  public void set$Id(UUID $id) {
    this.$id = $id;
  }

  public SkillCardsMetadata $parent(String $parent) {
    this.$parent = $parent;
    return this;
  }

   /**
   * An ID for the parent folder
   * @return $parent
  **/
  @Schema(example = "folder_59449484661,", description = "An ID for the parent folder")
  public String get$Parent() {
    return $parent;
  }

  public void set$Parent(String $parent) {
    this.$parent = $parent;
  }

  public SkillCardsMetadata $scope(String $scope) {
    this.$scope = $scope;
    return this;
  }

   /**
   * An ID for the scope in which this template has been applied
   * @return $scope
  **/
  @Schema(example = "enterprise_27335", description = "An ID for the scope in which this template has been applied")
  public String get$Scope() {
    return $scope;
  }

  public void set$Scope(String $scope) {
    this.$scope = $scope;
  }

  public SkillCardsMetadata $template(String $template) {
    this.$template = $template;
    return this;
  }

   /**
   * The name of the template
   * @return $template
  **/
  @Schema(example = "properties", description = "The name of the template")
  public String get$Template() {
    return $template;
  }

  public void set$Template(String $template) {
    this.$template = $template;
  }

  public SkillCardsMetadata $type(String $type) {
    this.$type = $type;
    return this;
  }

   /**
   * A unique identifier for the \&quot;type\&quot; of this instance. This is an internal system property and should not be used by a client application.
   * @return $type
  **/
  @Schema(example = "properties-6bcba49f-ca6d-4d2a-a758-57fe6edf44d0", description = "A unique identifier for the \"type\" of this instance. This is an internal system property and should not be used by a client application.")
  public String get$Type() {
    return $type;
  }

  public void set$Type(String $type) {
    this.$type = $type;
  }

  public SkillCardsMetadata $typeVersion(Integer $typeVersion) {
    this.$typeVersion = $typeVersion;
    return this;
  }

   /**
   * The last-known version of the template of the object. This is an internal system property and should not be used by a client application.
   * @return $typeVersion
  **/
  @Schema(example = "2", description = "The last-known version of the template of the object. This is an internal system property and should not be used by a client application.")
  public Integer get$TypeVersion() {
    return $typeVersion;
  }

  public void set$TypeVersion(Integer $typeVersion) {
    this.$typeVersion = $typeVersion;
  }

  public SkillCardsMetadata $version(Integer $version) {
    this.$version = $version;
    return this;
  }

   /**
   * The version of the metadata object. Starts at 0 and increases every time a user-defined property is modified.
   * @return $version
  **/
  @Schema(example = "1", description = "The version of the metadata object. Starts at 0 and increases every time a user-defined property is modified.")
  public Integer get$Version() {
    return $version;
  }

  public void set$Version(Integer $version) {
    this.$version = $version;
  }

  public SkillCardsMetadata cards(List<OneOfSkillCardsMetadataCardsItems> cards) {
    this.cards = cards;
    return this;
  }

  public SkillCardsMetadata addCardsItem(OneOfSkillCardsMetadataCardsItems cardsItem) {
    if (this.cards == null) {
      this.cards = new ArrayList<>();
    }
    this.cards.add(cardsItem);
    return this;
  }

   /**
   * A list of Box Skill cards that have been applied to this file.
   * @return cards
  **/
  @Schema(description = "A list of Box Skill cards that have been applied to this file.")
  public List<OneOfSkillCardsMetadataCardsItems> getCards() {
    return cards;
  }

  public void setCards(List<OneOfSkillCardsMetadataCardsItems> cards) {
    this.cards = cards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkillCardsMetadata skillCardsMetadata = (SkillCardsMetadata) o;
    return Objects.equals(this.$canEdit, skillCardsMetadata.$canEdit) &&
        Objects.equals(this.$id, skillCardsMetadata.$id) &&
        Objects.equals(this.$parent, skillCardsMetadata.$parent) &&
        Objects.equals(this.$scope, skillCardsMetadata.$scope) &&
        Objects.equals(this.$template, skillCardsMetadata.$template) &&
        Objects.equals(this.$type, skillCardsMetadata.$type) &&
        Objects.equals(this.$typeVersion, skillCardsMetadata.$typeVersion) &&
        Objects.equals(this.$version, skillCardsMetadata.$version) &&
        Objects.equals(this.cards, skillCardsMetadata.cards);
  }

  @Override
  public int hashCode() {
    return Objects.hash($canEdit, $id, $parent, $scope, $template, $type, $typeVersion, $version, cards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkillCardsMetadata {\n");
    
    sb.append("    $canEdit: ").append(toIndentedString($canEdit)).append("\n");
    sb.append("    $id: ").append(toIndentedString($id)).append("\n");
    sb.append("    $parent: ").append(toIndentedString($parent)).append("\n");
    sb.append("    $scope: ").append(toIndentedString($scope)).append("\n");
    sb.append("    $template: ").append(toIndentedString($template)).append("\n");
    sb.append("    $type: ").append(toIndentedString($type)).append("\n");
    sb.append("    $typeVersion: ").append(toIndentedString($typeVersion)).append("\n");
    sb.append("    $version: ").append(toIndentedString($version)).append("\n");
    sb.append("    cards: ").append(toIndentedString(cards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
