/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.box.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import ch.cyberduck.core.box.io.swagger.client.model.WebhooksTarget;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;
/**
 * Represents a configured webhook.
 */
@Schema(description = "Represents a configured webhook.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-25T11:35:18.602705+01:00[Europe/Zurich]")
public class Webhook {
  @JsonProperty("id")
  private String id = null;

  /**
   * &#x60;webhook&#x60;
   */
  public enum TypeEnum {
    WEBHOOK("webhook");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("target")
  private WebhooksTarget target = null;

  @JsonProperty("created_by")
  private AllOfWebhookCreatedBy createdBy = null;

  @JsonProperty("created_at")
  private DateTime createdAt = null;

  @JsonProperty("address")
  private String address = null;

  /**
   * The event name that triggered this webhook
   */
  public enum TriggersEnum {
    FILE_UPLOADED("FILE.UPLOADED"),
    FILE_PREVIEWED("FILE.PREVIEWED"),
    FILE_DOWNLOADED("FILE.DOWNLOADED"),
    FILE_TRASHED("FILE.TRASHED"),
    FILE_DELETED("FILE.DELETED"),
    FILE_RESTORED("FILE.RESTORED"),
    FILE_COPIED("FILE.COPIED"),
    FILE_MOVED("FILE.MOVED"),
    FILE_LOCKED("FILE.LOCKED"),
    FILE_UNLOCKED("FILE.UNLOCKED"),
    FILE_RENAMED("FILE.RENAMED"),
    COMMENT_CREATED("COMMENT.CREATED"),
    COMMENT_UPDATED("COMMENT.UPDATED"),
    COMMENT_DELETED("COMMENT.DELETED"),
    TASK_ASSIGNMENT_CREATED("TASK_ASSIGNMENT.CREATED"),
    TASK_ASSIGNMENT_UPDATED("TASK_ASSIGNMENT.UPDATED"),
    METADATA_INSTANCE_CREATED("METADATA_INSTANCE.CREATED"),
    METADATA_INSTANCE_UPDATED("METADATA_INSTANCE.UPDATED"),
    METADATA_INSTANCE_DELETED("METADATA_INSTANCE.DELETED"),
    FOLDER_CREATED("FOLDER.CREATED"),
    FOLDER_RENAMED("FOLDER.RENAMED"),
    FOLDER_DOWNLOADED("FOLDER.DOWNLOADED"),
    FOLDER_RESTORED("FOLDER.RESTORED"),
    FOLDER_DELETED("FOLDER.DELETED"),
    FOLDER_COPIED("FOLDER.COPIED"),
    FOLDER_MOVED("FOLDER.MOVED"),
    FOLDER_TRASHED("FOLDER.TRASHED"),
    WEBHOOK_DELETED("WEBHOOK.DELETED"),
    COLLABORATION_CREATED("COLLABORATION.CREATED"),
    COLLABORATION_ACCEPTED("COLLABORATION.ACCEPTED"),
    COLLABORATION_REJECTED("COLLABORATION.REJECTED"),
    COLLABORATION_REMOVED("COLLABORATION.REMOVED"),
    COLLABORATION_UPDATED("COLLABORATION.UPDATED"),
    SHARED_LINK_DELETED("SHARED_LINK.DELETED"),
    SHARED_LINK_CREATED("SHARED_LINK.CREATED"),
    SHARED_LINK_UPDATED("SHARED_LINK.UPDATED");

    private String value;

    TriggersEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TriggersEnum fromValue(String text) {
      for (TriggersEnum b : TriggersEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("triggers")
  private List<TriggersEnum> triggers = null;

  public Webhook id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for this webhook.
   * @return id
  **/
  @Schema(example = "11446498", description = "The unique identifier for this webhook.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Webhook type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * &#x60;webhook&#x60;
   * @return type
  **/
  @Schema(example = "webhook", description = "`webhook`")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Webhook target(WebhooksTarget target) {
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  @Schema(description = "")
  public WebhooksTarget getTarget() {
    return target;
  }

  public void setTarget(WebhooksTarget target) {
    this.target = target;
  }

  public Webhook createdBy(AllOfWebhookCreatedBy createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @Schema(description = "")
  public AllOfWebhookCreatedBy getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(AllOfWebhookCreatedBy createdBy) {
    this.createdBy = createdBy;
  }

  public Webhook createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * A timestamp identifying the time that the webhook was created.
   * @return createdAt
  **/
  @Schema(example = "2012-12-12T10:53:43-08:00", description = "A timestamp identifying the time that the webhook was created.")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Webhook address(String address) {
    this.address = address;
    return this;
  }

   /**
   * The URL that is notified by this webhook
   * @return address
  **/
  @Schema(example = "https://example.com/webhooks", description = "The URL that is notified by this webhook")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public Webhook triggers(List<TriggersEnum> triggers) {
    this.triggers = triggers;
    return this;
  }

  public Webhook addTriggersItem(TriggersEnum triggersItem) {
    if (this.triggers == null) {
      this.triggers = new ArrayList<>();
    }
    this.triggers.add(triggersItem);
    return this;
  }

   /**
   * An array of event names that this webhook is to be triggered for
   * @return triggers
  **/
  @Schema(example = "[\"FILE.UPLOADED\"]", description = "An array of event names that this webhook is to be triggered for")
  public List<TriggersEnum> getTriggers() {
    return triggers;
  }

  public void setTriggers(List<TriggersEnum> triggers) {
    this.triggers = triggers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Webhook webhook = (Webhook) o;
    return Objects.equals(this.id, webhook.id) &&
        Objects.equals(this.type, webhook.type) &&
        Objects.equals(this.target, webhook.target) &&
        Objects.equals(this.createdBy, webhook.createdBy) &&
        Objects.equals(this.createdAt, webhook.createdAt) &&
        Objects.equals(this.address, webhook.address) &&
        Objects.equals(this.triggers, webhook.triggers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, target, createdBy, createdAt, address, triggers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Webhook {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
