/*
 * DRACOON
 * REST Web Services for DRACOON<br>Version: 4.11.2  - built at: 2019-05-03 12:34:42<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.11.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DEPRECATED Branding information
 */
@ApiModel(description = "DEPRECATED Branding information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-17T14:22:07.810+02:00")
public class BrandingServerInfo {
  @JsonProperty("brandingServerBrandingId")
  private String brandingServerBrandingId = null;

  @JsonProperty("brandingServerCustomer")
  private String brandingServerCustomer = null;

  @JsonProperty("brandingServerUrl")
  private String brandingServerUrl = null;

  public BrandingServerInfo brandingServerBrandingId(String brandingServerBrandingId) {
    this.brandingServerBrandingId = brandingServerBrandingId;
    return this;
  }

   /**
   * UUID of Branding
   * @return brandingServerBrandingId
  **/
  @ApiModelProperty(required = true, value = "UUID of Branding")
  public String getBrandingServerBrandingId() {
    return brandingServerBrandingId;
  }

  public void setBrandingServerBrandingId(String brandingServerBrandingId) {
    this.brandingServerBrandingId = brandingServerBrandingId;
  }

  public BrandingServerInfo brandingServerCustomer(String brandingServerCustomer) {
    this.brandingServerCustomer = brandingServerCustomer;
    return this;
  }

   /**
    * &#x60;DEPRECATED&#x60;: Branding server customer UUID  [Deprecated since version 4.6.0]
   * @return brandingServerCustomer
  **/
   @ApiModelProperty(required = true, value = "`DEPRECATED`: Branding server customer UUID  [Deprecated since version 4.6.0]")
  public String getBrandingServerCustomer() {
    return brandingServerCustomer;
  }

  public void setBrandingServerCustomer(String brandingServerCustomer) {
    this.brandingServerCustomer = brandingServerCustomer;
  }

  public BrandingServerInfo brandingServerUrl(String brandingServerUrl) {
    this.brandingServerUrl = brandingServerUrl;
    return this;
  }

   /**
    * &#x60;DEPRECATED&#x60;: Branding server URL  [Deprecated since version 4.6.0]
   * @return brandingServerUrl
  **/
   @ApiModelProperty(example = "https://www.random-url.com", value = "`DEPRECATED`: Branding server URL  [Deprecated since version 4.6.0]")
  public String getBrandingServerUrl() {
    return brandingServerUrl;
  }

  public void setBrandingServerUrl(String brandingServerUrl) {
    this.brandingServerUrl = brandingServerUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrandingServerInfo brandingServerInfo = (BrandingServerInfo) o;
    return Objects.equals(this.brandingServerBrandingId, brandingServerInfo.brandingServerBrandingId) &&
        Objects.equals(this.brandingServerCustomer, brandingServerInfo.brandingServerCustomer) &&
        Objects.equals(this.brandingServerUrl, brandingServerInfo.brandingServerUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brandingServerBrandingId, brandingServerCustomer, brandingServerUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrandingServerInfo {\n");

      sb.append("    brandingServerBrandingId: ").append(toIndentedString(brandingServerBrandingId)).append("\n");
    sb.append("    brandingServerCustomer: ").append(toIndentedString(brandingServerCustomer)).append("\n");
    sb.append("    brandingServerUrl: ").append(toIndentedString(brandingServerUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

