/*
 * DRACOON API
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * OpenAPI spec version: 4.45.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Notification channel information
 */
@Schema(description = "Notification channel information")

public class NotificationChannel {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("isEnabled")
  private Boolean isEnabled = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("frequency")
  private Long frequency = null;

  public NotificationChannel id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Channel ID
   * @return id
  **/
  @Schema(required = true, description = "Channel ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public NotificationChannel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name
   * @return name
  **/
  @Schema(required = true, description = "Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NotificationChannel isEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * Determines whether channel is enabled
   * @return isEnabled
  **/
  @Schema(required = true, description = "Determines whether channel is enabled")
  public Boolean isIsEnabled() {
    return isEnabled;
  }

  public void setIsEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }

  public NotificationChannel type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Channel type (only &#x60;EMAIL&#x60; available at the moment)
   * @return type
  **/
  @Schema(required = true, description = "Channel type (only `EMAIL` available at the moment)")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public NotificationChannel frequency(Long frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Channel frequency (aggregation window size in minutes)
   * @return frequency
  **/
  @Schema(required = true, description = "Channel frequency (aggregation window size in minutes)")
  public Long getFrequency() {
    return frequency;
  }

  public void setFrequency(Long frequency) {
    this.frequency = frequency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationChannel notificationChannel = (NotificationChannel) o;
    return Objects.equals(this.id, notificationChannel.id) &&
        Objects.equals(this.name, notificationChannel.name) &&
        Objects.equals(this.isEnabled, notificationChannel.isEnabled) &&
        Objects.equals(this.type, notificationChannel.type) &&
        Objects.equals(this.frequency, notificationChannel.frequency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, isEnabled, type, frequency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationChannel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
