/*
 * DRACOON
 * REST Web Services for DRACOON<br>Version: 4.11.2  - built at: 2019-05-03 12:34:42<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.11.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Request model for handling pending assignments
 */
@ApiModel(description = "Request model for handling pending assignments")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-05-17T14:22:07.810+02:00")
public class PendingAssignmentsRequest {
  @JsonProperty("items")
  private List<PendingAssignment> items = new ArrayList<>();

  public PendingAssignmentsRequest items(List<PendingAssignment> items) {
    this.items = items;
    return this;
  }

  public PendingAssignmentsRequest addItemsItem(PendingAssignment itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * List of pending assignments
   * @return items
  **/
  @ApiModelProperty(required = true, value = "List of pending assignments")
  public List<PendingAssignment> getItems() {
    return items;
  }

  public void setItems(List<PendingAssignment> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PendingAssignmentsRequest pendingAssignmentsRequest = (PendingAssignmentsRequest) o;
    return Objects.equals(this.items, pendingAssignmentsRequest.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PendingAssignmentsRequest {\n");

      sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

