/*
 * DRACOON
 * REST Web Services for DRACOON<br>Version: 4.20.1  - built at: 2020-04-05 23:00:17<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.20.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Pending group information (DEPRECATED)
 */
@ApiModel(description = "Pending group information (DEPRECATED)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-08T17:57:49.759+02:00")
public class PendingGroupData {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  public PendingGroupData id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * &#x60;DEPRECATED&#x60;: Unique identifier for the group use &#x60;id&#x60; from &#x60;GroupInfo&#x60; instead  [Deprecated since version 4.11.0]
   * @return id
  **/
  @ApiModelProperty(required = true, value = "`DEPRECATED`: Unique identifier for the group use `id` from `GroupInfo` instead  [Deprecated since version 4.11.0]")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PendingGroupData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * &#x60;DEPRECATED&#x60;: Group name use &#x60;name&#x60; from &#x60;GroupInfo&#x60; instead  [Deprecated since version 4.11.0]
   * @return name
  **/
  @ApiModelProperty(required = true, value = "`DEPRECATED`: Group name use `name` from `GroupInfo` instead  [Deprecated since version 4.11.0]")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PendingGroupData pendingGroupData = (PendingGroupData) o;
    return Objects.equals(this.id, pendingGroupData.id) &&
        Objects.equals(this.name, pendingGroupData.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PendingGroupData {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

