/*
 * DRACOON API
 * REST Web Services for DRACOON<br><br>This page provides an overview of all available and documented DRACOON APIs, which are grouped by tags.<br>Each tag provides a collection of APIs that are intended for a specific area of the DRACOON.<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a><br><br><a title='Terms of service' href='https://www.dracoon.com/terms/general-terms-and-conditions/'>Terms of service</a>
 *
 * OpenAPI spec version: 4.45.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import ch.cyberduck.core.sds.io.swagger.client.model.Feature;
import ch.cyberduck.core.sds.io.swagger.client.model.FeaturedOAuthClient;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ProductPackageResponse
 */
@Schema(description = "ProductPackageResponse")

public class ProductPackageResponse {
  @JsonProperty("productPackageId")
  private Long productPackageId = null;

  @JsonProperty("productPackageName")
  private String productPackageName = null;

  @JsonProperty("features")
  private List<Feature> features = new ArrayList<>();

  @JsonProperty("clients")
  private List<FeaturedOAuthClient> clients = new ArrayList<>();

  public ProductPackageResponse productPackageId(Long productPackageId) {
    this.productPackageId = productPackageId;
    return this;
  }

   /**
   * ID
   * @return productPackageId
  **/
  @Schema(required = true, description = "ID")
  public Long getProductPackageId() {
    return productPackageId;
  }

  public void setProductPackageId(Long productPackageId) {
    this.productPackageId = productPackageId;
  }

  public ProductPackageResponse productPackageName(String productPackageName) {
    this.productPackageName = productPackageName;
    return this;
  }

   /**
   * Name
   * @return productPackageName
  **/
  @Schema(required = true, description = "Name")
  public String getProductPackageName() {
    return productPackageName;
  }

  public void setProductPackageName(String productPackageName) {
    this.productPackageName = productPackageName;
  }

  public ProductPackageResponse features(List<Feature> features) {
    this.features = features;
    return this;
  }

  public ProductPackageResponse addFeaturesItem(Feature featuresItem) {
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Features
   * @return features
  **/
  @Schema(required = true, description = "Features")
  public List<Feature> getFeatures() {
    return features;
  }

  public void setFeatures(List<Feature> features) {
    this.features = features;
  }

  public ProductPackageResponse clients(List<FeaturedOAuthClient> clients) {
    this.clients = clients;
    return this;
  }

  public ProductPackageResponse addClientsItem(FeaturedOAuthClient clientsItem) {
    this.clients.add(clientsItem);
    return this;
  }

   /**
   * OAuth Client Information
   * @return clients
  **/
  @Schema(required = true, description = "OAuth Client Information")
  public List<FeaturedOAuthClient> getClients() {
    return clients;
  }

  public void setClients(List<FeaturedOAuthClient> clients) {
    this.clients = clients;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductPackageResponse productPackageResponse = (ProductPackageResponse) o;
    return Objects.equals(this.productPackageId, productPackageResponse.productPackageId) &&
        Objects.equals(this.productPackageName, productPackageResponse.productPackageName) &&
        Objects.equals(this.features, productPackageResponse.features) &&
        Objects.equals(this.clients, productPackageResponse.clients);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productPackageId, productPackageName, features, clients);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductPackageResponse {\n");
    
    sb.append("    productPackageId: ").append(toIndentedString(productPackageId)).append("\n");
    sb.append("    productPackageName: ").append(toIndentedString(productPackageName)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    clients: ").append(toIndentedString(clients)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
