/*
 * DRACOON
 * REST Web Services for DRACOON<br>Version: 4.8.0-LTS  - built at: 2018-05-03 15:44:37<br><br><a title='Developer Information' href='https://developer.dracoon.com'>Developer Information</a>&emsp;&emsp;<a title='Get SDKs on GitHub' href='https://github.com/dracoon'>Get SDKs on GitHub</a>
 *
 * OpenAPI spec version: 4.8.0-LTS
 * Contact: develop@dracoon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.sds.io.swagger.client.model;

/*
 * Copyright (c) 2002-2018 iterate GmbH. All rights reserved.
 * https://cyberduck.io/
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

import org.joda.time.DateTime;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * PublicDownloadShare
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-23T09:31:14.222+02:00")
public class PublicDownloadShare {
  @JsonProperty("isProtected")
  private Boolean isProtected = null;

  @JsonProperty("fileName")
  private String fileName = null;

  @JsonProperty("size")
  private Long size = null;

  @JsonProperty("limitReached")
  private Boolean limitReached = null;

  @JsonProperty("creatorName")
  private String creatorName = null;

  @JsonProperty("createdAt")
  private DateTime createdAt = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("creatorUsername")
  private String creatorUsername = null;

  @JsonProperty("expireAt")
  private DateTime expireAt = null;

  @JsonProperty("notes")
  private String notes = null;

  @JsonProperty("isEncrypted")
  private Boolean isEncrypted = null;

  @JsonProperty("fileKey")
  private FileKey fileKey = null;

  @JsonProperty("privateKeyContainer")
  private PrivateKeyContainer privateKeyContainer = null;

  public PublicDownloadShare isProtected(Boolean isProtected) {
    this.isProtected = isProtected;
    return this;
  }

   /**
   * Is share protected by password
   * @return isProtected
  **/
  @ApiModelProperty(example = "false", required = true, value = "Is share protected by password")
  public Boolean getIsProtected() {
    return isProtected;
  }

  public void setIsProtected(Boolean isProtected) {
    this.isProtected = isProtected;
  }

  public PublicDownloadShare fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * File name
   * @return fileName
  **/
  @ApiModelProperty(required = true, value = "File name")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public PublicDownloadShare size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * File size or container size not compressed (in bytes)
   * @return size
  **/
  @ApiModelProperty(required = true, value = "File size or container size not compressed (in bytes)")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public PublicDownloadShare limitReached(Boolean limitReached) {
    this.limitReached = limitReached;
    return this;
  }

   /**
   * Downloads limit reached
   * @return limitReached
  **/
  @ApiModelProperty(example = "false", required = true, value = "Downloads limit reached")
  public Boolean getLimitReached() {
    return limitReached;
  }

  public void setLimitReached(Boolean limitReached) {
    this.limitReached = limitReached;
  }

  public PublicDownloadShare creatorName(String creatorName) {
    this.creatorName = creatorName;
    return this;
  }

   /**
   * Creator name
   * @return creatorName
  **/
  @ApiModelProperty(required = true, value = "Creator name")
  public String getCreatorName() {
    return creatorName;
  }

  public void setCreatorName(String creatorName) {
    this.creatorName = creatorName;
  }

  public PublicDownloadShare createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Creation date
   * @return createdAt
  **/
  @ApiModelProperty(example = "2018-01-01T00:00:00", required = true, value = "Creation date")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public PublicDownloadShare name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Share display name (alias name)
   * @return name
  **/
  @ApiModelProperty(value = "Share display name (alias name)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PublicDownloadShare creatorUsername(String creatorUsername) {
    this.creatorUsername = creatorUsername;
    return this;
  }

   /**
   * Creator user name
   * @return creatorUsername
  **/
  @ApiModelProperty(value = "Creator user name")
  public String getCreatorUsername() {
    return creatorUsername;
  }

  public void setCreatorUsername(String creatorUsername) {
    this.creatorUsername = creatorUsername;
  }

  public PublicDownloadShare expireAt(DateTime expireAt) {
    this.expireAt = expireAt;
    return this;
  }

   /**
   * Expiration date
   * @return expireAt
  **/
  @ApiModelProperty(example = "2018-01-01T00:00:00", value = "Expiration date")
  public DateTime getExpireAt() {
    return expireAt;
  }

  public void setExpireAt(DateTime expireAt) {
    this.expireAt = expireAt;
  }

  public PublicDownloadShare notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * User notes (limited to 255 characters)
   * @return notes
  **/
  @ApiModelProperty(value = "User notes (limited to 255 characters)")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public PublicDownloadShare isEncrypted(Boolean isEncrypted) {
    this.isEncrypted = isEncrypted;
    return this;
  }

   /**
   * Encryption state
   * @return isEncrypted
  **/
  @ApiModelProperty(example = "false", value = "Encryption state")
  public Boolean getIsEncrypted() {
    return isEncrypted;
  }

  public void setIsEncrypted(Boolean isEncrypted) {
    this.isEncrypted = isEncrypted;
  }

  public PublicDownloadShare fileKey(FileKey fileKey) {
    this.fileKey = fileKey;
    return this;
  }

   /**
   * Encrypted file key for shares out of encrypted rooms
   * @return fileKey
  **/
  @ApiModelProperty(value = "Encrypted file key for shares out of encrypted rooms")
  public FileKey getFileKey() {
    return fileKey;
  }

  public void setFileKey(FileKey fileKey) {
    this.fileKey = fileKey;
  }

  public PublicDownloadShare privateKeyContainer(PrivateKeyContainer privateKeyContainer) {
    this.privateKeyContainer = privateKeyContainer;
    return this;
  }

   /**
   * Private key container (private key and version)
   * @return privateKeyContainer
  **/
  @ApiModelProperty(value = "Private key container (private key and version)")
  public PrivateKeyContainer getPrivateKeyContainer() {
    return privateKeyContainer;
  }

  public void setPrivateKeyContainer(PrivateKeyContainer privateKeyContainer) {
    this.privateKeyContainer = privateKeyContainer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicDownloadShare publicDownloadShare = (PublicDownloadShare) o;
    return Objects.equals(this.isProtected, publicDownloadShare.isProtected) &&
        Objects.equals(this.fileName, publicDownloadShare.fileName) &&
        Objects.equals(this.size, publicDownloadShare.size) &&
        Objects.equals(this.limitReached, publicDownloadShare.limitReached) &&
        Objects.equals(this.creatorName, publicDownloadShare.creatorName) &&
        Objects.equals(this.createdAt, publicDownloadShare.createdAt) &&
        Objects.equals(this.name, publicDownloadShare.name) &&
        Objects.equals(this.creatorUsername, publicDownloadShare.creatorUsername) &&
        Objects.equals(this.expireAt, publicDownloadShare.expireAt) &&
        Objects.equals(this.notes, publicDownloadShare.notes) &&
        Objects.equals(this.isEncrypted, publicDownloadShare.isEncrypted) &&
        Objects.equals(this.fileKey, publicDownloadShare.fileKey) &&
        Objects.equals(this.privateKeyContainer, publicDownloadShare.privateKeyContainer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isProtected, fileName, size, limitReached, creatorName, createdAt, name, creatorUsername, expireAt, notes, isEncrypted, fileKey, privateKeyContainer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicDownloadShare {\n");

    sb.append("    isProtected: ").append(toIndentedString(isProtected)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    limitReached: ").append(toIndentedString(limitReached)).append("\n");
    sb.append("    creatorName: ").append(toIndentedString(creatorName)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    creatorUsername: ").append(toIndentedString(creatorUsername)).append("\n");
    sb.append("    expireAt: ").append(toIndentedString(expireAt)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    isEncrypted: ").append(toIndentedString(isEncrypted)).append("\n");
    sb.append("    fileKey: ").append(toIndentedString(fileKey)).append("\n");
    sb.append("    privateKeyContainer: ").append(toIndentedString(privateKeyContainer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

