/*
 * DRACOON
 * Version 4.4.0 - built at: 2017-12-04 04:14:43, API server: https://demo.dracoon.com/api/v4
 *
 * OpenAPI spec version: 4.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RadiusChallengeResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T10:55:56.129+02:00")
public class RadiusChallengeResponse {
  @JsonProperty("code")
  private Integer code = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("debugInfo")
  private String debugInfo = null;

  @JsonProperty("errorCode")
  private Integer errorCode = null;

  @JsonProperty("replyState")
  private String replyState = null;

  @JsonProperty("replyMessage")
  private String replyMessage = null;

  public RadiusChallengeResponse code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * HTTP status code
   * @return code
  **/
  @ApiModelProperty(value = "HTTP status code")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public RadiusChallengeResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * HTTP status code description
   * @return message
  **/
  @ApiModelProperty(value = "HTTP status code description")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public RadiusChallengeResponse debugInfo(String debugInfo) {
    this.debugInfo = debugInfo;
    return this;
  }

   /**
   * Debug information
   * @return debugInfo
  **/
  @ApiModelProperty(value = "Debug information")
  public String getDebugInfo() {
    return debugInfo;
  }

  public void setDebugInfo(String debugInfo) {
    this.debugInfo = debugInfo;
  }

  public RadiusChallengeResponse errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Error code
   * @return errorCode
  **/
  @ApiModelProperty(value = "Error code")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public RadiusChallengeResponse replyState(String replyState) {
    this.replyState = replyState;
    return this;
  }

   /**
   * Radius State. If a replyState is returned, it must be included as \&quot;state\&quot; in the following request
   * @return replyState
  **/
  @ApiModelProperty(value = "Radius State. If a replyState is returned, it must be included as \"state\" in the following request")
  public String getReplyState() {
    return replyState;
  }

  public void setReplyState(String replyState) {
    this.replyState = replyState;
  }

  public RadiusChallengeResponse replyMessage(String replyMessage) {
    this.replyMessage = replyMessage;
    return this;
  }

   /**
   * Radius Reply-Message. Instruction how to handle the situation.
   * @return replyMessage
  **/
  @ApiModelProperty(value = "Radius Reply-Message. Instruction how to handle the situation.")
  public String getReplyMessage() {
    return replyMessage;
  }

  public void setReplyMessage(String replyMessage) {
    this.replyMessage = replyMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RadiusChallengeResponse radiusChallengeResponse = (RadiusChallengeResponse) o;
    return Objects.equals(this.code, radiusChallengeResponse.code) &&
        Objects.equals(this.message, radiusChallengeResponse.message) &&
        Objects.equals(this.debugInfo, radiusChallengeResponse.debugInfo) &&
        Objects.equals(this.errorCode, radiusChallengeResponse.errorCode) &&
        Objects.equals(this.replyState, radiusChallengeResponse.replyState) &&
        Objects.equals(this.replyMessage, radiusChallengeResponse.replyMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, debugInfo, errorCode, replyState, replyMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RadiusChallengeResponse {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    debugInfo: ").append(toIndentedString(debugInfo)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    replyState: ").append(toIndentedString(replyState)).append("\n");
    sb.append("    replyMessage: ").append(toIndentedString(replyMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

