/*
 * DRACOON
 * Version 4.4.0 - built at: 2017-12-04 04:14:43, API server: https://demo.dracoon.com/api/v4
 *
 * OpenAPI spec version: 4.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ch.cyberduck.core.sds.io.swagger.client.model;

import java.util.Objects;
import ch.cyberduck.core.sds.io.swagger.client.model.CustomerData;
import ch.cyberduck.core.sds.io.swagger.client.model.RoleList;
import ch.cyberduck.core.sds.io.swagger.client.model.UserAttributes;
import ch.cyberduck.core.sds.io.swagger.client.model.UserAuthMethod;
import ch.cyberduck.core.sds.io.swagger.client.model.UserGroup;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * UserAccount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-03T10:55:56.129+02:00")
public class UserAccount {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("login")
  private String login = null;

  @JsonProperty("needsToChangeUserName")
  private Boolean needsToChangeUserName = null;

  @JsonProperty("needsToChangePassword")
  private Boolean needsToChangePassword = null;

  @JsonProperty("needsToAcceptEULA")
  private Boolean needsToAcceptEULA = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  /**
   * Gender key, one of [m|f|n]
   */
  public enum GenderEnum {
    M("m"),
    
    F("f"),
    
    N("n");

    private String value;

    GenderEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GenderEnum fromValue(String text) {
      for (GenderEnum b : GenderEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("gender")
  private GenderEnum gender = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("lockStatus")
  private Integer lockStatus = null;

  @JsonProperty("expireAt")
  private java.util.Date expireAt = null;

  @JsonProperty("hasManageableRooms")
  private Boolean hasManageableRooms = null;

  @JsonProperty("isEncryptionEnabled")
  private Boolean isEncryptionEnabled = null;

  @JsonProperty("lastLoginSuccessAt")
  private java.util.Date lastLoginSuccessAt = null;

  @JsonProperty("lastLoginSuccessIp")
  private String lastLoginSuccessIp = null;

  @JsonProperty("lastLoginFailAt")
  private java.util.Date lastLoginFailAt = null;

  @JsonProperty("lastLoginFailIp")
  private String lastLoginFailIp = null;

  @JsonProperty("customer")
  private CustomerData customer = null;

  @JsonProperty("userRoles")
  private RoleList userRoles = null;

  @JsonProperty("userGroups")
  private List<UserGroup> userGroups = null;

  @JsonProperty("userAttributes")
  private UserAttributes userAttributes = null;

  @JsonProperty("authMethods")
  private List<UserAuthMethod> authMethods = new ArrayList<UserAuthMethod>();

  public UserAccount id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the user
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Unique identifier for the user")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UserAccount login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Login name
   * @return login
  **/
  @ApiModelProperty(required = true, value = "Login name")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public UserAccount needsToChangeUserName(Boolean needsToChangeUserName) {
    this.needsToChangeUserName = needsToChangeUserName;
    return this;
  }

   /**
   * User must change the user login name
   * @return needsToChangeUserName
  **/
  @ApiModelProperty(value = "User must change the user login name")
  public Boolean getNeedsToChangeUserName() {
    return needsToChangeUserName;
  }

  public void setNeedsToChangeUserName(Boolean needsToChangeUserName) {
    this.needsToChangeUserName = needsToChangeUserName;
  }

  public UserAccount needsToChangePassword(Boolean needsToChangePassword) {
    this.needsToChangePassword = needsToChangePassword;
    return this;
  }

   /**
   * User has changed the password
   * @return needsToChangePassword
  **/
  @ApiModelProperty(required = true, value = "User has changed the password")
  public Boolean getNeedsToChangePassword() {
    return needsToChangePassword;
  }

  public void setNeedsToChangePassword(Boolean needsToChangePassword) {
    this.needsToChangePassword = needsToChangePassword;
  }

  public UserAccount needsToAcceptEULA(Boolean needsToAcceptEULA) {
    this.needsToAcceptEULA = needsToAcceptEULA;
    return this;
  }

   /**
   * User has accepted EULA. Present, if EULA is system global active. See: Get system settings -&gt; eula_active
   * @return needsToAcceptEULA
  **/
  @ApiModelProperty(value = "User has accepted EULA. Present, if EULA is system global active. See: Get system settings -> eula_active")
  public Boolean getNeedsToAcceptEULA() {
    return needsToAcceptEULA;
  }

  public void setNeedsToAcceptEULA(Boolean needsToAcceptEULA) {
    this.needsToAcceptEULA = needsToAcceptEULA;
  }

  public UserAccount title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Job title
   * @return title
  **/
  @ApiModelProperty(value = "Job title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public UserAccount firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * First name
   * @return firstName
  **/
  @ApiModelProperty(required = true, value = "First name")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserAccount lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Last name
   * @return lastName
  **/
  @ApiModelProperty(required = true, value = "Last name")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserAccount gender(GenderEnum gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Gender key, one of [m|f|n]
   * @return gender
  **/
  @ApiModelProperty(value = "Gender key, one of [m|f|n]")
  public GenderEnum getGender() {
    return gender;
  }

  public void setGender(GenderEnum gender) {
    this.gender = gender;
  }

  public UserAccount email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email [NOT USED]
   * @return email
  **/
  @ApiModelProperty(value = "Email [NOT USED]")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserAccount lockStatus(Integer lockStatus) {
    this.lockStatus = lockStatus;
    return this;
  }

   /**
   * Lock status: 0 - Locked, 1 - Web access allowed, 2 - Web and mobile access allowed
   * @return lockStatus
  **/
  @ApiModelProperty(required = true, value = "Lock status: 0 - Locked, 1 - Web access allowed, 2 - Web and mobile access allowed")
  public Integer getLockStatus() {
    return lockStatus;
  }

  public void setLockStatus(Integer lockStatus) {
    this.lockStatus = lockStatus;
  }

  public UserAccount expireAt(java.util.Date expireAt) {
    this.expireAt = expireAt;
    return this;
  }

   /**
   * Account expiration date (2015-12-31T23:59:00)
   * @return expireAt
  **/
  @ApiModelProperty(value = "Account expiration date (2015-12-31T23:59:00)")
  public java.util.Date getExpireAt() {
    return expireAt;
  }

  public void setExpireAt(java.util.Date expireAt) {
    this.expireAt = expireAt;
  }

  public UserAccount hasManageableRooms(Boolean hasManageableRooms) {
    this.hasManageableRooms = hasManageableRooms;
    return this;
  }

   /**
   * User has manageable rooms
   * @return hasManageableRooms
  **/
  @ApiModelProperty(required = true, value = "User has manageable rooms")
  public Boolean getHasManageableRooms() {
    return hasManageableRooms;
  }

  public void setHasManageableRooms(Boolean hasManageableRooms) {
    this.hasManageableRooms = hasManageableRooms;
  }

  public UserAccount isEncryptionEnabled(Boolean isEncryptionEnabled) {
    this.isEncryptionEnabled = isEncryptionEnabled;
    return this;
  }

   /**
   * User has generated private key. Possible if &lt;b&gt;Triple-Crypt&amp;trade; Technology&lt;/b&gt; is active for this customer
   * @return isEncryptionEnabled
  **/
  @ApiModelProperty(value = "User has generated private key. Possible if <b>Triple-Crypt&trade; Technology</b> is active for this customer")
  public Boolean getIsEncryptionEnabled() {
    return isEncryptionEnabled;
  }

  public void setIsEncryptionEnabled(Boolean isEncryptionEnabled) {
    this.isEncryptionEnabled = isEncryptionEnabled;
  }

  public UserAccount lastLoginSuccessAt(java.util.Date lastLoginSuccessAt) {
    this.lastLoginSuccessAt = lastLoginSuccessAt;
    return this;
  }

   /**
   * Last successful logon date (2015-12-31T23:59:00)
   * @return lastLoginSuccessAt
  **/
  @ApiModelProperty(value = "Last successful logon date (2015-12-31T23:59:00)")
  public java.util.Date getLastLoginSuccessAt() {
    return lastLoginSuccessAt;
  }

  public void setLastLoginSuccessAt(java.util.Date lastLoginSuccessAt) {
    this.lastLoginSuccessAt = lastLoginSuccessAt;
  }

  public UserAccount lastLoginSuccessIp(String lastLoginSuccessIp) {
    this.lastLoginSuccessIp = lastLoginSuccessIp;
    return this;
  }

   /**
   * Last successful logon IP address
   * @return lastLoginSuccessIp
  **/
  @ApiModelProperty(value = "Last successful logon IP address")
  public String getLastLoginSuccessIp() {
    return lastLoginSuccessIp;
  }

  public void setLastLoginSuccessIp(String lastLoginSuccessIp) {
    this.lastLoginSuccessIp = lastLoginSuccessIp;
  }

  public UserAccount lastLoginFailAt(java.util.Date lastLoginFailAt) {
    this.lastLoginFailAt = lastLoginFailAt;
    return this;
  }

   /**
   * Last failed logon date (2015-12-31T23:59:00)
   * @return lastLoginFailAt
  **/
  @ApiModelProperty(value = "Last failed logon date (2015-12-31T23:59:00)")
  public java.util.Date getLastLoginFailAt() {
    return lastLoginFailAt;
  }

  public void setLastLoginFailAt(java.util.Date lastLoginFailAt) {
    this.lastLoginFailAt = lastLoginFailAt;
  }

  public UserAccount lastLoginFailIp(String lastLoginFailIp) {
    this.lastLoginFailIp = lastLoginFailIp;
    return this;
  }

   /**
   * Last failed logon IP address
   * @return lastLoginFailIp
  **/
  @ApiModelProperty(value = "Last failed logon IP address")
  public String getLastLoginFailIp() {
    return lastLoginFailIp;
  }

  public void setLastLoginFailIp(String lastLoginFailIp) {
    this.lastLoginFailIp = lastLoginFailIp;
  }

  public UserAccount customer(CustomerData customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Customer data
   * @return customer
  **/
  @ApiModelProperty(required = true, value = "Customer data")
  public CustomerData getCustomer() {
    return customer;
  }

  public void setCustomer(CustomerData customer) {
    this.customer = customer;
  }

  public UserAccount userRoles(RoleList userRoles) {
    this.userRoles = userRoles;
    return this;
  }

   /**
   * User assignment roles
   * @return userRoles
  **/
  @ApiModelProperty(required = true, value = "User assignment roles")
  public RoleList getUserRoles() {
    return userRoles;
  }

  public void setUserRoles(RoleList userRoles) {
    this.userRoles = userRoles;
  }

  public UserAccount userGroups(List<UserGroup> userGroups) {
    this.userGroups = userGroups;
    return this;
  }

  public UserAccount addUserGroupsItem(UserGroup userGroupsItem) {
    if (this.userGroups == null) {
      this.userGroups = new ArrayList<UserGroup>();
    }
    this.userGroups.add(userGroupsItem);
    return this;
  }

   /**
   * All groups the user is member of.
   * @return userGroups
  **/
  @ApiModelProperty(value = "All groups the user is member of.")
  public List<UserGroup> getUserGroups() {
    return userGroups;
  }

  public void setUserGroups(List<UserGroup> userGroups) {
    this.userGroups = userGroups;
  }

  public UserAccount userAttributes(UserAttributes userAttributes) {
    this.userAttributes = userAttributes;
    return this;
  }

   /**
   * Custom user attributes; visible if more_info &#x3D; true
   * @return userAttributes
  **/
  @ApiModelProperty(value = "Custom user attributes; visible if more_info = true")
  public UserAttributes getUserAttributes() {
    return userAttributes;
  }

  public void setUserAttributes(UserAttributes userAttributes) {
    this.userAttributes = userAttributes;
  }

  public UserAccount authMethods(List<UserAuthMethod> authMethods) {
    this.authMethods = authMethods;
    return this;
  }

  public UserAccount addAuthMethodsItem(UserAuthMethod authMethodsItem) {
    this.authMethods.add(authMethodsItem);
    return this;
  }

   /**
   * Authentication methods
   * @return authMethods
  **/
  @ApiModelProperty(required = true, value = "Authentication methods")
  public List<UserAuthMethod> getAuthMethods() {
    return authMethods;
  }

  public void setAuthMethods(List<UserAuthMethod> authMethods) {
    this.authMethods = authMethods;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAccount userAccount = (UserAccount) o;
    return Objects.equals(this.id, userAccount.id) &&
        Objects.equals(this.login, userAccount.login) &&
        Objects.equals(this.needsToChangeUserName, userAccount.needsToChangeUserName) &&
        Objects.equals(this.needsToChangePassword, userAccount.needsToChangePassword) &&
        Objects.equals(this.needsToAcceptEULA, userAccount.needsToAcceptEULA) &&
        Objects.equals(this.title, userAccount.title) &&
        Objects.equals(this.firstName, userAccount.firstName) &&
        Objects.equals(this.lastName, userAccount.lastName) &&
        Objects.equals(this.gender, userAccount.gender) &&
        Objects.equals(this.email, userAccount.email) &&
        Objects.equals(this.lockStatus, userAccount.lockStatus) &&
        Objects.equals(this.expireAt, userAccount.expireAt) &&
        Objects.equals(this.hasManageableRooms, userAccount.hasManageableRooms) &&
        Objects.equals(this.isEncryptionEnabled, userAccount.isEncryptionEnabled) &&
        Objects.equals(this.lastLoginSuccessAt, userAccount.lastLoginSuccessAt) &&
        Objects.equals(this.lastLoginSuccessIp, userAccount.lastLoginSuccessIp) &&
        Objects.equals(this.lastLoginFailAt, userAccount.lastLoginFailAt) &&
        Objects.equals(this.lastLoginFailIp, userAccount.lastLoginFailIp) &&
        Objects.equals(this.customer, userAccount.customer) &&
        Objects.equals(this.userRoles, userAccount.userRoles) &&
        Objects.equals(this.userGroups, userAccount.userGroups) &&
        Objects.equals(this.userAttributes, userAccount.userAttributes) &&
        Objects.equals(this.authMethods, userAccount.authMethods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, login, needsToChangeUserName, needsToChangePassword, needsToAcceptEULA, title, firstName, lastName, gender, email, lockStatus, expireAt, hasManageableRooms, isEncryptionEnabled, lastLoginSuccessAt, lastLoginSuccessIp, lastLoginFailAt, lastLoginFailIp, customer, userRoles, userGroups, userAttributes, authMethods);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAccount {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    needsToChangeUserName: ").append(toIndentedString(needsToChangeUserName)).append("\n");
    sb.append("    needsToChangePassword: ").append(toIndentedString(needsToChangePassword)).append("\n");
    sb.append("    needsToAcceptEULA: ").append(toIndentedString(needsToAcceptEULA)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    lockStatus: ").append(toIndentedString(lockStatus)).append("\n");
    sb.append("    expireAt: ").append(toIndentedString(expireAt)).append("\n");
    sb.append("    hasManageableRooms: ").append(toIndentedString(hasManageableRooms)).append("\n");
    sb.append("    isEncryptionEnabled: ").append(toIndentedString(isEncryptionEnabled)).append("\n");
    sb.append("    lastLoginSuccessAt: ").append(toIndentedString(lastLoginSuccessAt)).append("\n");
    sb.append("    lastLoginSuccessIp: ").append(toIndentedString(lastLoginSuccessIp)).append("\n");
    sb.append("    lastLoginFailAt: ").append(toIndentedString(lastLoginFailAt)).append("\n");
    sb.append("    lastLoginFailIp: ").append(toIndentedString(lastLoginFailIp)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    userRoles: ").append(toIndentedString(userRoles)).append("\n");
    sb.append("    userGroups: ").append(toIndentedString(userGroups)).append("\n");
    sb.append("    userAttributes: ").append(toIndentedString(userAttributes)).append("\n");
    sb.append("    authMethods: ").append(toIndentedString(authMethods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

