name: Publish App Store

on:
  push:
    tags: [ '*' ]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      maven-profiles: '!local,appstore,sandbox'
      platform: macos
      sparkle-feed: ''
      publish: false
    secrets: inherit

  appstore:
    needs: deploy
    permissions:
      actions: read
      contents: read
    runs-on: macos
    steps:
      - name: Download App PKG (macOS)
        uses: actions/download-artifact@v7
        with:
          pattern: Cyberduck-*.pkg
          path: release
          merge-multiple: true
      - name: Upload to App Store
        env:
          NOTARIZATION_USER: ${{ secrets.NOTARIZATION_USER }}
          NOTARIZATION_PW: ${{ secrets.NOTARIZATION_PW }}
        run: xcrun altool --verbose --upload-app -f release/*.pkg -t osx -u "$NOTARIZATION_USER" -p "$NOTARIZATION_PW"
