name: Publish Mac App Store

on:
  push:
    tags: [ '*' ]

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      MAVEN_PROFILES: '!local,appstore,sandbox'
      PLATFORM: macos
      SPARKLE_FEED: ''
      DEVELOPER_DIR: '/Applications/Xcode 26.app/Contents/Developer'
    secrets: inherit

  appstore:
    needs: deploy
    permissions:
      actions: read
      contents: read
    runs-on: macos
    steps:
      - name: Download App PKG (macOS)
        uses: actions/download-artifact@v7
        with:
          pattern: Cyberduck-*.pkg
          path: release
          merge-multiple: true
      - name: Upload to Mac App Store
        env:
          NOTARIZATION_USER: ${{ secrets.NOTARIZATION_USER }}
          NOTARIZATION_PW: ${{ secrets.NOTARIZATION_PW }}
        run: xcrun altool --verbose --upload-app -f release/*.pkg -t osx -u "$NOTARIZATION_USER" -p "$NOTARIZATION_PW"
