name: Publish Snapshot
on:
  push:
    branches:
      - master
jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos, windows, linux, linux-arm64 ]
    uses: ./.github/workflows/deploy.yml
    with:
      SPARKLE_FEED: nightly
      PLATFORM: ${{ matrix['platform'] }}
      DEVELOPER_DIR: '/Applications/Xcode 26.app/Contents/Developer'
      SIGNTOOL_CSP: 'Google Cloud KMS Provider'
      SIGNTOOL_KC: 'projects/api-project-996125414232/locations/europe/keyRings/code-signing/cryptoKeys/windows/cryptoKeyVersions/1'
      CODESIGN_CERTIFICATE: 'Developer ID Application: David Kocher (G69SCX94XU)'
      INSTALLER_CERTIFICATE: 'Developer ID Installer: David Kocher (G69SCX94XU)'
      CODESIGN_PROVISIONPROFILE_NAME: 'default.provisionprofile'
      CODESIGN_ENTITLEMENTS_NAME: 'default.entitlements'
    secrets: inherit

  publish:
    needs: deploy
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/publish.yml
    with:
      SPARKLE_FEED: nightly
    secrets: inherit
