name: Publish Snapshot
on:
  push:
    branches:
      - master
jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos, arch: arm64, goal: deploy }
          - { os: windows, arch: x64, goal: deploy }
          - { os: linux, arch: x64, goal: deploy }
          - { os: linux, arch: arm64, goal: deploy }
    uses: ./.github/workflows/deploy.yml
    with:
      SPARKLE_FEED: nightly
      RUNNER_OS: ${{ matrix.os }}
      RUNNER_ARCH: ${{ matrix.arch }}
      MAVEN_GOAL: ${{ matrix.goal }}
      DEVELOPER_DIR: '/Applications/Xcode 26.app/Contents/Developer'
      SIGNTOOL_CSP: 'Google Cloud KMS Provider'
      SIGNTOOL_KC: 'projects/api-project-996125414232/locations/europe/keyRings/code-signing/cryptoKeys/windows/cryptoKeyVersions/1'
      CODESIGN_CERTIFICATE: 'Developer ID Application: David Kocher (G69SCX94XU)'
      INSTALLER_CERTIFICATE: 'Developer ID Installer: David Kocher (G69SCX94XU)'
      CODESIGN_PROVISIONPROFILE_NAME: 'default.provisionprofile'
      CODESIGN_ENTITLEMENTS_NAME: 'default.entitlements'
    secrets: inherit

  publish:
    needs: deploy
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/publish.yml
    with:
      SPARKLE_FEED: nightly
    secrets: inherit
